'use strict';

Object.defineProperty(exports, '__esModule', { value: true });

var config_URLConfig = require('./config/URLConfig.cjs');
var config_CloudConfig = require('./config/CloudConfig.cjs');
var config_CloudinaryConfig = require('./config/CloudinaryConfig.cjs');
var transformation_Transformation = require('./transformation/Transformation.cjs');
var transformation_ImageTransformation = require('./transformation/ImageTransformation.cjs');
var transformation_VideoTransformation = require('./transformation/VideoTransformation.cjs');
var assets_CloudinaryImage = require('./assets/CloudinaryImage.cjs');
var assets_CloudinaryVideo = require('./assets/CloudinaryVideo.cjs');
var assets_CloudinaryFile = require('./assets/CloudinaryFile.cjs');
var assets_CloudinaryMedia = require('./assets/CloudinaryMedia.cjs');
var instance_Cloudinary = require('./instance/Cloudinary.cjs');
var backwards_createCloudinaryLegacyURL = require('./backwards/createCloudinaryLegacyURL.cjs');
var actions = require('./actions-b8965aed.cjs');
var qualifiers = require('./qualifiers-6fa11bc8.cjs');
require('./tslib.es6-f1398b83.cjs');
require('./config/BaseConfig.cjs');
require('./internal/internalConstants.cjs');
require('./internal/utils/objectFlip.cjs');
require('./internal/Action.cjs');
require('./qualifiers/flag/FlagQualifier.cjs');
require('./internal/qualifier/QualifierValue.cjs');
require('./internal/qualifier/Qualifier.cjs');
require('./internal/models/QualifierModel.cjs');
require('./internal/models/qualifierToJson.cjs');
require('./internal/utils/unsupportedError.cjs');
require('./internal/utils/dataStructureUtils.cjs');
require('./internal/models/ActionModel.cjs');
require('./internal/models/actionToJson.cjs');
require('./actions/background/actions/BackgroundColor.cjs');
require('./internal/utils/prepareColor.cjs');
require('./internal/RawAction.cjs');
require('./internal/models/IErrorObject.cjs');
require('./assets/CloudinaryTransformable.cjs');
require('./actions/delivery/DeliveryFormatAction.cjs');
require('./qualifiers/flag.cjs');
require('./actions/delivery/DeliveryAction.cjs');
require('./qualifiers/format/FormatQualifier.cjs');
require('./qualifiers/progressive.cjs');
require('./internal/url/cloudinaryURL.cjs');
require('./internal/url/urlUtils/isUrl.cjs');
require('./internal/url/urlUtils/isFileName.cjs');
require('./internal/url/urlUtils/publicIDContainsVersion.cjs');
require('./sdkAnalytics/getSDKAnalyticsSignature.cjs');
require('./sdkAnalytics/encodeVersion.cjs');
require('./sdkAnalytics/base64Map.cjs');
require('./sdkAnalytics/stringPad.cjs');
require('./sdkAnalytics/reverseVersion.cjs');
require('./sdkAnalytics/getAnalyticsOptions.cjs');
require('./internal/utils/packageVersion.cjs');
require('./internal/utils/cloneDeep.cjs');
require('./backwards/generateTransformationString.cjs');
require('./backwards/transformationProcessing/processLayer.cjs');
require('./backwards/utils/isObject.cjs');
require('./internal/utils/base64Encode.cjs');
require('./backwards/consts.cjs');
require('./backwards/utils/smartEscape.cjs');
require('./backwards/legacyLayer/textlayer.cjs');
require('./backwards/legacyLayer/layer.cjs');
require('./backwards/utils/snakeCase.cjs');
require('./backwards/utils/isEmpty.cjs');
require('./backwards/utils/isNumberLike.cjs');
require('./backwards/transformationProcessing/processIf.cjs');
require('./backwards/utils/legacyNormalizeExpression.cjs');
require('./backwards/utils/toArray.cjs');
require('./backwards/transformationProcessing/processRadius.cjs');
require('./backwards/transformationProcessing/processCustomFunction.cjs');
require('./backwards/transformationProcessing/processCustomPreFunction.cjs');
require('./backwards/utils/splitRange.cjs');
require('./backwards/utils/norm_range_values.cjs');
require('./backwards/transformationProcessing/processVideoParams.cjs');
require('./backwards/transformation.cjs');
require('./backwards/condition.cjs');
require('./backwards/expression.cjs');
require('./backwards/configuration.cjs');
require('./backwards/utils/legacyBaseUtil.cjs');
require('./backwards/legacyLayer/subtitleslayer.cjs');
require('./backwards/legacyLayer/fetchlayer.cjs');
require('./backwards/utils/isFunction.cjs');
require('./backwards/transformationProcessing/processDpr.cjs');
require('./backwards/utils/finalizeResourceType.cjs');
require('./backwards/utils/finalize_source.cjs');
require('./backwards/utils/unsigned_url_prefix.cjs');
require('./actions/resize.cjs');
require('./actions/resize/ResizePadAction.cjs');
require('./actions/resize/ResizeAdvancedAction.cjs');
require('./actions/resize/ResizeSimpleAction.cjs');
require('./internal/utils/toFloatAsString.cjs');
require('./qualifiers/aspectRatio/AspectRatioQualifierValue.cjs');
require('./internal/models/createGravityModel.cjs');
require('./qualifiers/gravity/autoGravity/AutoGravity.cjs');
require('./qualifiers/gravity/GravityQualifier.cjs');
require('./qualifiers/gravity/focusOnGravity/FocusOnGravity.cjs');
require('./qualifiers/gravity.cjs');
require('./qualifiers/gravity/compassGravity/CompassGravity.cjs');
require('./qualifiers/gravity/xyCenterGravity/XYCenterGravity.cjs');
require('./qualifiers/gravity/qualifiers/focusOn/FocusOnValue.cjs');
require('./internal/models/createGravityFromModel.cjs');
require('./qualifiers/focusOn.cjs');
require('./qualifiers/autoFocus.cjs');
require('./qualifiers/gravity/qualifiers/compass/CompassQualifier.cjs');
require('./internal/models/createBackgroundModel.cjs');
require('./qualifiers/background/shared/BlurredBackgroundAction.cjs');
require('./qualifiers/background/shared/base/BackgroundQualifier.cjs');
require('./qualifiers/background/shared/auto/BackgroundAutoBorderQualifier.cjs');
require('./qualifiers/background/shared/base/BaseCommonBackground.cjs');
require('./qualifiers/background/shared/gradient/BackgroundBorderGradientQualifier.cjs');
require('./qualifiers/background/shared/base/BaseGradientBackground.cjs');
require('./qualifiers/background/shared/gradient/BackgroundPredominantGradientQualifier.cjs');
require('./qualifiers/background/shared/auto/BackgroundAutoPredominantQualifier.cjs');
require('./internal/models/createBackgroundFromModel.cjs');
require('./qualifiers/rotate/RotationModeQualifierValue.cjs');
require('./qualifiers/region/CustomRegion.cjs');
require('./qualifiers/region/NamedRegion.cjs');
require('./qualifiers/position/PositionQualifier.cjs');
require('./qualifiers/gradientDirection/GradientDirectionQualifierValue.cjs');
require('./qualifiers/expression/ExpressionQualifier.cjs');
require('./qualifiers/background.cjs');
require('./qualifiers/animatedFormat/AnimatedFormatQualifierValue.cjs');
require('./qualifiers/source/sourceTypes/VideoSource.cjs');
require('./qualifiers/source/BaseSource.cjs');
require('./qualifiers/source/sourceTypes/ImageSource.cjs');
require('./qualifiers/source/sourceTypes/SubtitlesSource.cjs');
require('./qualifiers/source/sourceTypes/BaseTextSource.cjs');
require('./qualifiers/textStyle.cjs');
require('./qualifiers/fontWeight.cjs');
require('./qualifiers/fontStyle.cjs');
require('./qualifiers/textDecoration.cjs');
require('./internal/utils/serializeCloudinaryCharacters.cjs');
require('./qualifiers/textStroke.cjs');
require('./internal/models/IStrokeModel.cjs');
require('./qualifiers/source/sourceTypes/FetchSource.cjs');
require('./qualifiers/source/sourceTypes/TextSource.cjs');
require('./internal/models/createTextStyleFromModel.cjs');
require('./actions/resize/ResizeScaleAction.cjs');
require('./actions/resize/ThumbnailAction.cjs');
require('./actions/resize/ResizeCropAction.cjs');
require('./actions/resize/ResizeFillAction.cjs');
require('./actions/resize/ResizeLimitFitAction.cjs');
require('./actions/resize/ResizeLimitFillAction.cjs');
require('./actions/resize/ResizeLimitPadAction.cjs');
require('./actions/resize/ResizeMinimumPadAction.cjs');
require('./actions/border.cjs');
require('./actions/roundCorners.cjs');
require('./actions/roundCorners/RoundCornersAction.cjs');
require('./actions/effect.cjs');
require('./actions/effect/blur/Blur.cjs');
require('./qualifiers/region.cjs');
require('./actions/effect/leveled/Accelerate.cjs');
require('./actions/effect/leveled/Loop.cjs');
require('./actions/effect/EffectActions/LeveledEffectAction.cjs');
require('./actions/effect/EffectActions/SimpleEffectAction.cjs');
require('./actions/effect/Cartoonify.cjs');
require('./actions/effect/Outline.cjs');
require('./actions/effect/leveled/MakeTransparent.cjs');
require('./actions/effect/Vectorize.cjs');
require('./actions/effect/SimulateColorBlind.cjs');
require('./actions/effect/EffectActions/EffectActionWithLevel.cjs');
require('./actions/effect/AssistColorBlind.cjs');
require('./actions/effect/GradientFade.cjs');
require('./actions/effect/leveled/FadeOut.cjs');
require('./actions/effect/Colorize.cjs');
require('./actions/effect/Shadow.cjs');
require('./actions/effect/StyleTransfer.cjs');
require('./actions/effect/Dither.cjs');
require('./actions/effect/leveled/Deshake.cjs');
require('./actions/effect/pixelate/Pixelate.cjs');
require('./actions/effect/EffectActions/EffectActionWithStrength.cjs');
require('./actions/effect/leveled/Blackwhite.cjs');
require('./actions/effect/leveled/FadeIn.cjs');
require('./actions/effect/RemoveBackgroundAction.cjs');
require('./actions/effect/Theme.cjs');
require('./actions/rotate.cjs');
require('./actions/rotate/RotateAction.cjs');
require('./actions/adjust.cjs');
require('./actions/adjust/FillLightAction.cjs');
require('./actions/adjust/RecolorAction.cjs');
require('./actions/adjust/OpacityAdjustAction.cjs');
require('./actions/adjust/By3dLutAction.cjs');
require('./actions/adjust/ImproveAction.cjs');
require('./actions/adjust/ReplaceColorAction.cjs');
require('./actions/effect/EffectActions/EffectActionWithBlend.cjs');
require('./actions/adjust/simple/ViesusCorrectAdjustAction.cjs');
require('./actions/overlay.cjs');
require('./actions/layer/LayerAction.cjs');
require('./qualifiers/blendMode/BlendModeQualifier.cjs');
require('./internal/models/createSourceFromModel.cjs');
require('./internal/models/IImageSourceModel.cjs');
require('./internal/models/IFetchSourceModel.cjs');
require('./internal/models/ITextSourceModel.cjs');
require('./internal/models/createPositionFromModel.cjs');
require('./internal/models/createTimelinePositionFromModel.cjs');
require('./qualifiers/video/TimelinePosition.cjs');
require('./actions/underlay.cjs');
require('./actions/namedTransformation.cjs');
require('./actions/namedTransformation/NamedTransformationAction.cjs');
require('./actions/delivery.cjs');
require('./actions/delivery/DeliveryQualityAction.cjs');
require('./actions/delivery/DeliveryColorSpaceFromICCAction.cjs');
require('./actions/delivery/DeliveryColorSpaceAction.cjs');
require('./qualifiers/colorSpace.cjs');
require('./actions/delivery/DeliveryDPRAction.cjs');
require('./actions/customFunction.cjs');
require('./actions/customFunction/CustomFunctionAction.cjs');
require('./actions/customFunction/RemoteAction.cjs');
require('./actions/videoEdit.cjs');
require('./actions/videoEdit/TrimAction.cjs');
require('./actions/videoEdit/ConcatenateAction.cjs');
require('./actions/videoEdit/VolumeAction.cjs');
require('./actions/videoEdit/PreviewAction.cjs');
require('./actions/transcode.cjs');
require('./actions/transcode/BitRateAction.cjs');
require('./actions/transcode/AudioCodecAction.cjs');
require('./actions/transcode/AudioFrequencyAction.cjs');
require('./actions/transcode/FPSAction.cjs');
require('./actions/transcode/FPSRangeAction.cjs');
require('./actions/transcode/KeyframeIntervalsAction.cjs');
require('./actions/transcode/StreamingProfile.cjs');
require('./actions/transcode/ToAnimatedAction.cjs');
require('./actions/transcode/VideoCodecAction.cjs');
require('./qualifiers/videoCodecType/VideoCodecType.cjs');
require('./qualifiers/videoCodec.cjs');
require('./actions/psdTools.cjs');
require('./actions/psdTools/ClipAction.cjs');
require('./actions/psdTools/GetLayerAction.cjs');
require('./actions/psdTools/SmartObjectAction.cjs');
require('./actions/animated.cjs');
require('./qualifiers/textAlignment.cjs');
require('./qualifiers/streamingProfile.cjs');
require('./qualifiers/simulateColorBlind.cjs');
require('./qualifiers/rotationMode.cjs');
require('./qualifiers/quality.cjs');
require('./qualifiers/outlineMode.cjs');
require('./qualifiers/improveMode.cjs');
require('./qualifiers/gradientDirection.cjs');
require('./qualifiers/format.cjs');
require('./qualifiers/fontHinting.cjs');
require('./qualifiers/expression.cjs');
require('./qualifiers/dither.cjs');
require('./qualifiers/color.cjs');
require('./qualifiers/audioFrequency.cjs');
require('./qualifiers/audioCodec.cjs');
require('./qualifiers/aspectRatio.cjs');
require('./qualifiers/artisticFilter.cjs');
require('./qualifiers/animatedFormat.cjs');
require('./qualifiers/chromaSubSampling.cjs');
require('./qualifiers/dpr.cjs');
require('./qualifiers/source.cjs');
require('./qualifiers/GradientFade.cjs');



exports.URLConfig = config_URLConfig;
exports.CloudConfig = config_CloudConfig;
exports.CloudinaryConfig = config_CloudinaryConfig;
exports.Transformation = transformation_Transformation.Transformation;
exports.ImageTransformation = transformation_ImageTransformation.ImageTransformation;
exports.VideoTransformation = transformation_VideoTransformation.VideoTransformation;
exports.CloudinaryImage = assets_CloudinaryImage.CloudinaryImage;
exports.CloudinaryVideo = assets_CloudinaryVideo.CloudinaryVideo;
exports.CloudinaryFile = assets_CloudinaryFile.CloudinaryFile;
exports.CloudinaryMedia = assets_CloudinaryMedia.CloudinaryMedia;
exports.Cloudinary = instance_Cloudinary.Cloudinary;
exports.createCloudinaryLegacyURL = backwards_createCloudinaryLegacyURL.createCloudinaryLegacyURL;
exports.Actions = actions.actions;
exports.Qualifiers = qualifiers.qualifiers;
