export enum AppType {
  Root = 'Explore Apps',
  Blog = 'Blog',
  Bridge = 'Bridge',
  Swap = 'Swap',
  xSwap = 'xSwap',
  Furo = 'Streaming',
  Legacy = 'Sushi 1.0',
  Internal = 'Internal',
  Kashi = 'Lend & Borrow',
  Analytics = 'Analytics',
  Earn = 'Earn',
  Partner = 'Partner',
  Widget = 'Widget',
  Academy = 'Academy',
}
