import type { Token } from '~stellar/_common/lib/types/token.type'

// These are MAINNET tokens (curated by StellarExpert)
// See: https://api.stellar.expert/explorer/public/asset-list/top50
export const baseTokens: Token[] = [
  {
    code: 'XLM',
    issuer: 'GDMTVHLWJTHSUDMZVVMXXH6VJHA2ZV3HNG5LYNAZ6RTWB7GISM6PGTUV',
    contract: 'CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA',
    name: 'XLM',
    org: 'stellar',
    domain: 'stellar.org',
    decimals: 7,
  },
  {
    code: 'USDC',
    issuer: 'GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN',
    contract: 'CCW67TSZV3SSS2HXMBQ5JFGCKJNXKZM7UQUWUZPUTHXSTZLEO7SJMI75',
    name: 'USDC',
    org: 'centre',
    domain: 'centre.io',
    decimals: 7,
    isStable: true,
  },
  {
    code: 'EURC',
    issuer: 'GDHU6WRG4IEQXM5NZ4BMPKOXHW76MZM4Y2IEMFDVXBSDP6SJY4ITNPP2',
    contract: 'CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV',
    name: 'EURC',
    org: 'centre',
    domain: 'circle.com',
    decimals: 7,
  },
  {
    code: 'PYUSD',
    issuer: 'GDQE7IXJ4HUHV6RQHIUPRJSEZE4DRS5WY577O2FY6YQ5LVWZ7JZTU2V5',
    contract: 'CCCRWH6Q3FNP3I2I57BDLM5AFAT7O6OF6GKQOC6SSJNDAVRZ57SPHGU2',
    name: 'PYUSD',
    org: 'paxos',
    domain: 'paxos.com',
    decimals: 7,
  },
  {
    code: 'USDY',
    issuer: 'GAJMPX5NBOG6TQFPQGRABJEEB2YE7RFRLUKJDZAZGAD5GFX4J7TADAZ6',
    contract: 'CB3YA656OYIHU57657I5KGSBRHE5I3OZU4VFC22PYAOANFZHEWNYGAGP',
    name: 'USDY',
    org: 'ondo',
    domain: 'ondo.finance',
    decimals: 7,
  },
  {
    code: 'SolvBTC',
    issuer: '',
    contract: 'CBIJBDNZNF4X35BJ4FFZWCDBSCKOP5NB4PLG4SNENRMLAPYG4P5FM6VN',
    name: 'Solv BTC',
    org: 'solv',
    domain: 'solv.finance',
    decimals: 8,
  },
  {
    code: 'xSolvBTC',
    issuer: '',
    contract: 'CAUP7NFABXE5TJRL3FKTPMWRLC7IAXYDCTHQRFSCLR5TMGKHOOQO772J',
    name: 'xSolvBTC',
    org: 'solv',
    domain: 'solv.finance',
    decimals: 8,
  },
  {
    code: 'CETES',
    issuer: 'GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC',
    contract: 'CAL6ER2TI6CTRAY6BFXWNWA7WTYXUXTQCHUBCIBU5O6KM3HJFG6Z6VXV',
    name: 'CETES',
    org: 'etherfuse',
    domain: 'etherfuse.com',
    decimals: 7,
  },
  {
    code: 'USTRY',
    issuer: 'GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC',
    contract: 'CBLV4ATSIWU67CFSQU2NVRKINQIKUZ2ODSZBUJTJ43VJVRSBTZYOPNUR',
    name: 'USTRY',
    org: 'etherfuse',
    domain: 'etherfuse.com',
    decimals: 7,
  },
  {
    code: 'TESOURO',
    issuer: 'GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC',
    contract: 'CD6M4R2322BYCY2LNWM74PEBQAQ63SA3DUJLI3L4225U4ZVCLMSCBCIS',
    name: 'TESOURO',
    org: 'etherfuse',
    domain: 'etherfuse.com',
    decimals: 7,
  },
  {
    code: 'MEX',
    issuer: 'GCRYUGD5NVARGXT56XEZI5CIFCQETYHAPQQTHO2O3IQZTHDH4LATMYWC',
    contract: 'CA4BHPZHZAFLKFRNBIQLEMAYIRWNC7T74ML4L5HTNPZPUZMWUPTSE5Q3',
    name: 'MEX',
    org: 'etherfuse',
    domain: 'etherfuse.com',
    decimals: 7,
  },
  {
    code: 'AQUA',
    issuer: 'GBNZILSTVQZ4R7IKQDGHYGY2QXL5QOFJYQMXPKWRRM5PAV7Y4M67AQUA',
    contract: 'CAUIKL3IYGMERDRUN6YSCLWVAKIFG5Q4YJHUKM4S4NJZQIA3BAS6OJPK',
    name: 'AQUA',
    org: 'unknown',
    domain: 'aqua.network',
    decimals: 7,
  },
  {
    code: 'yXLM',
    issuer: 'GARDNV3Q7YGT4AKSDF25LT32YSCCW4EV22Y2TV3I2PU2MMXJTEDL5T55',
    contract: 'CBZVSNVB55ANF24QVJL2K5QCLOAB6XITGTGXYEAF6NPTXYKEJUYQOHFC',
    name: 'yXLM',
    org: 'unknown',
    domain: 'ultracapital.xyz',
    decimals: 7,
  },
  {
    code: 'SHX',
    issuer: 'GDSTRSHXHGJ7ZIVRBXEYE5Q74XUVCUSEKEBR7UCHEUUEK72N7I7KJ6JH',
    contract: 'CCKCKCPHYVXQD4NECBFJTFSCU2AMSJGCNG4O6K4JVRE2BLPR7WNDBQIQ',
    name: 'SHX',
    org: 'unknown',
    domain: 'stronghold.co',
    decimals: 7,
  },
  {
    code: 'XRP',
    issuer: 'GBXRPL45NPHCVMFFAYZVUVFFVKSIZ362ZXFP7I2ETNQ3QKZMFLPRDTD5',
    contract: 'CAAV3AE3VKD2P4TY7LWTQMMJHIJ4WOCZ5ANCIJPC3NRSERKVXNHBU2W7',
    name: 'XRP',
    org: 'unknown',
    domain: 'fchain.io',
    decimals: 7,
  },
  {
    code: 'yUSDC',
    issuer: 'GDGTVWSM4MGS4T7Z6W4RPWOCHE2I6RDFCIFZGS3DOA63LWQTRNZNTTFF',
    contract: 'CDOFW7HNKLUZRLFZST4EW7V3AV4JI5IHMT6BPXXSY2IEFZ4NE5TWU2P4',
    name: 'yUSDC',
    org: 'unknown',
    domain: 'ultracapital.xyz',
    decimals: 7,
    isStable: true,
  },
  {
    code: 'SSLX',
    issuer: 'GBHFGY3ZNEJWLNO4LBUKLYOCEK4V7ENEBJGPRHHX7JU47GWHBREH37UR',
    contract: 'CBHBD77PWZ3AXPQVYVDBHDKEMVNOR26UZUZHWCB6QC7J5SETQPRUQAS4',
    name: 'SSLX',
    org: 'unknown',
    domain: 'sslx.sl8.online',
    decimals: 7,
  },
  {
    code: 'BTCLN',
    issuer: 'GDPKQ2TSNJOFSEE7XSUXPWRP27H6GFGLWD7JCHNEYYWQVGFA543EVBVT',
    contract: 'CBHIQPUXLFLC5O44ZJVUTCL5LMZFLVGU5DEIGSYKBSAPFMOGTKOQEPFM',
    name: 'BTCLN',
    org: 'unknown',
    domain: 'kbtrading.org',
    decimals: 7,
  },
  {
    code: 'VELO',
    issuer: 'GDM4RQUQQUVSKQA7S6EM7XBZP3FCGH4Q7CL6TABQ7B2BEJ5ERARM2M5M',
    contract: 'CAESLMGW5LYTIEJI7FJHK6SFSWRELLNVX5Q4WR4UZEALMTRWQDBKDPAG',
    name: 'VELO',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'XXA',
    issuer: 'GC4HS4CQCZULIOTGLLPGRAAMSBDLFRR6Y7HCUQG66LNQDISXKIXXADIM',
    contract: 'CBBJTE34KZHJACB2A6OXCRTDDLX4LI7GKYYD6XYJSGMX46BLNAG752HS',
    name: 'XXA',
    org: 'unknown',
    domain: 'ixinium.io',
    decimals: 7,
  },
  {
    code: 'SCOP',
    issuer: 'GC6OYQJIZF3HFXCYPFCBXYXNGIBQ4TNSFUBUXQJOZWIP6F3YZK4QH3VQ',
    contract: 'CCJVS6IVXAAXWCMFVK6QLWHZHR4RTVRSEZRQ53GOAEDN3VY2BLPVY72J',
    name: 'SCOP',
    org: 'unknown',
    domain: 'scopuly.com',
    decimals: 7,
  },
  {
    code: 'ARST',
    issuer: 'GCSAZVWXZKWS4XS223M5F54H2B6XPIIXZZGP7KEAIU6YSL5HDRGCI3DG',
    contract: 'CCRPYMVKZLWGZHEDZ23FOE22E3T3HOCNP5Y2EFZFVRUVIXU5NJ7UNGV2',
    name: 'ARST',
    org: 'unknown',
    domain: 'pubnet-sep.latamex.com',
    decimals: 7,
  },
  {
    code: 'AFR',
    issuer: 'GBX6YI45VU7WNAAKA3RBFDR3I3UKNFHTJPQ5F6KOOKSGYIAM4TRQN54W',
    contract: 'CCG27OZ5AV4WUXS6XTECWAXEY5UOMEFI2CWFA3LHZGBTLYZWTJF3MJYQ',
    name: 'AFR',
    org: 'unknown',
    domain: 'afreum.com',
    decimals: 7,
  },
  {
    code: 'BTC',
    issuer: 'GDPJALI4AZKUU2W426U5WKMAT6CN3AJRPIIRYR2YM54TL2GDWO5O2MZM',
    contract: 'CAO7DDJNGMOYQPRYDY5JVZ5YEK4UQBSMGLAEWRCUOTRMDSBMGWSAATDZ',
    name: 'BTC',
    org: 'unknown',
    domain: 'ultracapital.xyz',
    decimals: 7,
  },
  {
    code: 'ETH',
    issuer: 'GBFXOHVAS43OIWNIO7XLRJAHT3BICFEIKOJLZVXNT572MISM4CMGSOCC',
    contract: 'CBH4M45TQBLDPXOK6L7VYKMEJWFITBOL64BN3WDAIIDT4LNUTWTTOCKF',
    name: 'ETH',
    org: 'unknown',
    domain: 'ultracapital.xyz',
    decimals: 7,
  },
  {
    code: 'LSP',
    issuer: 'GAB7STHVD5BDH3EEYXPI3OM7PCS4V443PYB5FNT6CFGJVPDLMKDM24WK',
    contract: 'CBXE6V454EUYWVQCI4TCSOG4CSNPQ2BLYOTKAKXYFHO3KNVX4CXYCY2T',
    name: 'LSP',
    org: 'unknown',
    domain: 'lumenswap.io',
    decimals: 7,
  },
  {
    code: 'MOBI',
    issuer: 'GA6HCMBLTZS5VYYBCATRBRZ3BZJMAFUDKYYF6AH6MVCMGWMRDNSWJPIH',
    contract: 'CATHRLMZW3JUIYSXYE4YAI3SBBBQGXYAP674RINGUBQLNFTCZHMI5XZJ',
    name: 'MOBI',
    org: 'unknown',
    domain: 'mobius.network',
    decimals: 7,
  },
  {
    code: 'IDRT',
    issuer: 'GDPKQ2TSNJOFSEE7XSUXPWRP27H6GFGLWD7JCHNEYYWQVGFA543EVBVT',
    contract: 'CDYBK2X5ZEQ7ZNDN7IPWWMOQ6SWEJW4A4UE2PNDFDVCYNAXB64O4FNXX',
    name: 'IDRT',
    org: 'unknown',
    domain: 'kbtrading.org',
    decimals: 7,
  },
  {
    code: 'XTAR',
    issuer: 'GAORYJ3KBDGIM7FFSKVUJHJ5NEFWIRDIAGGBJBJS7TY6ECZS53257IG4',
    contract: 'CDCKFBZYF2AQCSM3JOF2ZM27O3Y6AJAI4OTCQKAFNZ3FHBYUTFOKICIY',
    name: 'XTAR',
    org: 'unknown',
    domain: 'dogstarcoin.com',
    decimals: 7,
  },
  {
    code: 'TFT',
    issuer: 'GBOVQKJYHXRR3DX6NOX2RRYFRCUMSADGDESTDNBDS6CDVLGVESRTAC47',
    contract: 'CCXY3CNHSU2DPUOZFKNNH67IVRMBRCATX4SABDSLBY5LAJI66LRLHTJQ',
    name: 'TFT',
    org: 'unknown',
    domain: 'threefold.io',
    decimals: 7,
  },
  {
    code: 'yBTC',
    issuer: 'GBUVRNH4RW4VLHP4C5MOF46RRIRZLAVHYGX45MVSTKA2F6TMR7E7L6NW',
    contract: 'CB2XMFB6BDIHFOSFB5IXHDOYV3SI3IXMNIZLPDZHC7ENDCXSBEBZAO2Y',
    name: 'yBTC',
    org: 'unknown',
    domain: 'ultracapital.xyz',
    decimals: 7,
  },
  {
    code: 'XCHF',
    issuer: 'GDPKQ2TSNJOFSEE7XSUXPWRP27H6GFGLWD7JCHNEYYWQVGFA543EVBVT',
    contract: 'CACFQEH2USDRGSBYFOVJMX4DMX7HMRYAYOV2IWR7XEX3DD3HYQEWPAAL',
    name: 'XCHF',
    org: 'unknown',
    domain: 'kbtrading.org',
    decimals: 7,
  },
  {
    code: 'SDEXEX',
    issuer: 'GBQHMDRWV3WU5YACBUUCBY4Y6PPWBJXW5WCSG5XJ63FC4HXJNGXYFD5J',
    contract: 'CDOIEBW5LN7T7PSFY6ADLPIDF52PFRX57WIYWJ637PCZ7ZFDDN5T6NCH',
    name: 'SDEXEX',
    org: 'unknown',
    domain: 'sdexexplorer.com',
    decimals: 7,
  },
  {
    code: 'BTC',
    issuer: 'GAUTUYY2THLF7SGITDFMXJVYH3LHDSMGEAKSBU267M2K7A3W543CKUEF',
    contract: 'CATJTQ2RWJ5VETWM7R3D43EZ55RUCOJTWV6FO4ACOKYLIRU52K3OBF6S',
    name: 'BTC',
    org: 'unknown',
    domain: 'dead.apay.io',
    decimals: 7,
  },
  {
    code: 'SLT',
    issuer: 'GCKA6K5PCQ6PNF5RQBF7PQDJWRHO6UOGFMRLK3DYHDOI244V47XKQ4GP',
    contract: 'CBDGSZPJ622XCHROYPRUFV3B3NEZOC23HW7LRBKJUVVWFUH6GE7NV3OD',
    name: 'SLT',
    org: 'unknown',
    domain: 'smartlands.io',
    decimals: 7,
  },
  {
    code: 'XRP',
    issuer: 'GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5',
    contract: 'CBPMFYWP4FFV7PQUYHXJZBXS75EHR6FXYSYEZWH2UM7AUYSKI2Z3PTCG',
    name: 'XRP',
    org: 'unknown',
    domain: 'stellarport.io',
    decimals: 7,
  },
  {
    code: 'FRED',
    issuer: 'GCA73U2PZFWAXJSNVMEVPNPPJCZGETWPWZC6E4DJAIWP3ZW3BAGYZLV6',
    contract: 'CDGLDM5N34GBRCALDBKVVV4ACVS2TWZLUSMILM32FPIMPHLUUIIRTCNF',
    name: 'FRED',
    org: 'unknown',
    domain: 'fredenergy.org',
    decimals: 7,
  },
  {
    code: 'BRL',
    issuer: 'GDVKY2GU2DRXWTBEYJJWSFXIGBZV6AZNBVVSUHEPZI54LIS6BA7DVVSP',
    contract: 'CBF4E5GSTVSITE5Q2ENOTEUQJPBZAU3SBDVLQMSQ7GLBRTSYGUAT722K',
    name: 'BRL',
    org: 'unknown',
    domain: 'ntokens.com',
    decimals: 7,
  },
  {
    code: 'Apay',
    issuer: 'GBDKPRMOLDHTVUFTQATMMFUBKRI372YPUTOSEH5SZAFRAAVADTUGSSMA',
    contract: 'CAIDUWYDM25GBIQVQQ5C7EFVLL2AKX35L6265ZOW2UKINZ6X6IYPDLZ4',
    name: 'Apay',
    org: 'unknown',
    domain: 'authenticpayment.stellarmint.io',
    decimals: 7,
  },
  {
    code: 'StellarNFT',
    issuer: 'GALZZQF5JXHPHGI5A2ZW2EPL76DU4DWSYYGTPLOAMMEQEEECFSSRIOZJ',
    contract: 'CAWSVMCGBT4YEDH4PK64TZ3IRTXDHZJ6PDSSUARFLKRG2H3MUBLTVQ6C',
    name: 'StellarNFT',
    org: 'unknown',
    domain: 'stellarnft.io',
    decimals: 7,
  },
  {
    code: 'EURC',
    issuer: 'GDHU6WRG4IEQXM5NZ4BMPKOXHW76MZM4Y2IEMFDVXBSDP6SJY4ITNPP2',
    contract: 'CDTKPWPLOURQA2SGTKTUQOWRCBZEORB4BWBOMJ3D3ZTQQSGE5F6JBQLV',
    name: 'EURC',
    org: 'unknown',
    domain: 'circle.com',
    decimals: 7,
  },
  {
    code: 'ZARZ',
    issuer: 'GAROH4EV3WVVTRQKEY43GZK3XSRBEYETRVZ7SVG5LHWOAANSMCTJBB3U',
    contract: 'CDXKEC5ADOVKR7U3BO3FV5DUODEFH5VFYCHZ5IXXQ6FI2VO6A36COPFG',
    name: 'ZARZ',
    org: 'unknown',
    domain: 'zeam.money',
    decimals: 7,
  },
  {
    code: 'TERN',
    issuer: 'GDGQDVO6XPFSY4NMX75A7AOVYCF5JYGW2SHCJJNWCQWIDGOZB53DGP6C',
    contract: 'CA5JIZ7DWWWGYYT6MNDUDXKLTVFD4LRK3OE55NMBHMX5EIPX6IDHEOCX',
    name: 'TERN',
    org: 'unknown',
    domain: 'ternio.io',
    decimals: 7,
  },
  {
    code: 'BTC',
    issuer: 'GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5',
    contract: 'CAIRIR3ITE2KNBWHRIAOBBZ2AHIKU5BVTKFTW5IYCOAENR4L5T2THGN6',
    name: 'BTC',
    org: 'unknown',
    domain: 'stellarport.io',
    decimals: 7,
  },
  {
    code: 'PYBC',
    issuer: 'GBVB43NLVIP2USHXSKI7QQCZKZU2Z6U6A5PAHMIW7LLNVMQJTOX2BZI5',
    contract: 'CDJXADCJHQJDAQQMUJU4TTRXS4ZAEFIA5F5RG4HP7M42CKQIZCXTCDR2',
    name: 'PYBC',
    org: 'unknown',
    domain: 'luxpayband.io',
    decimals: 7,
  },
  {
    code: 'ARS',
    issuer: 'GCYE7C77EB5AWAA25R5XMWNI2EDOKTTFTTPZKM2SR5DI4B4WFD52DARS',
    contract: 'CCD6H4LBTHAPY3NGEE6TLLRUSPJGX4K5XI2J6E4MUNDB5TNXEKC23H5B',
    name: 'ARS',
    org: 'unknown',
    domain: 'api.anclap.com',
    decimals: 7,
  },
  {
    code: 'yETH',
    issuer: 'GDYQNEF2UWTK4L6HITMT53MZ6F5QWO3Q4UVE6SCGC4OMEQIZQQDERQFD',
    contract: 'CDYEOOVL6WV4JRY45CXQKOBJFFAPOM5KNQCCDNM333L6RM2L4RO3LKYG',
    name: 'yETH',
    org: 'unknown',
    domain: 'ultracapital.xyz',
    decimals: 7,
  },
  {
    code: 'BRAVE',
    issuer: 'GDREF4TAC3RFYVLHEV24CXN2VBGCEEP74BZOC3T4Q4XJ6SXJFMDPNTJL',
    contract: 'CDRQND5ZVDRBRPVYRS5ZWZO3YCEO5PMCFVRDHEFFJLU4SRMBS2TGYHKF',
    name: 'BRAVE',
    org: 'unknown',
    domain: 'brave-token.age-shield.com',
    decimals: 7,
  },
  {
    code: 'EURMTL',
    issuer: 'GACKTN5DAZGWXRWB2WLM6OPBDHAMT6SJNGLJZPQMEZBUR4JUGBX2UK7V',
    contract: 'CDUYP3U6HGTOBUNQD2WTLWNMNADWMENROKZZIHGEVGKIU3ZUDF42CDOK',
    name: 'EURMTL',
    org: 'unknown',
    domain: 'mtl.montelibero.org',
    decimals: 7,
  },
  {
    code: 'SHAGGY',
    issuer: 'GBC4JTZSIDM6KNGJPHPNF7DKK3YXYLFLOQKL2OS755KV62BN4TRZC5U3',
    contract: 'CBGXQDSBO4PV3T4XMUVQDG74RII6WV2LU5DXIGDONBP77LHJCKL2QJEP',
    name: 'SHAGGY',
    org: 'unknown',
    domain: 'shaggy-token.com',
    decimals: 7,
  },
  {
    code: 'YBX',
    issuer: 'GBUYYBXWCLT2MOSSHRFCKMEDFOVSCAXNIEW424GLN666OEXHAAWBDYMX',
    contract: 'CBRP2VD3CZLEQIQZ4JMBXGA5AC2U6JE26YU5CCIOICIZCVWPGBO2QRUB',
    name: 'YBX',
    org: 'unknown',
    domain: 'script3.io',
    decimals: 7,
  },
  {
    code: 'NUNA',
    issuer: 'GCX2ENOVSSOOH6G4HIOBMPCBFXHDVDGA546NK3ZFX3NP3QS25BKZBWOW',
    contract: 'CAPIOPSODD5QP4SJNIS4ASUWML4LH7ZEKTAPBJYZSMKXCATEKDZFKLHK',
    name: 'NUNA',
    org: 'unknown',
    domain: 'nunaproject.art',
    decimals: 7,
  },
  {
    code: 'NLT',
    issuer: 'GAX25ZVO4JVPEDK3R7EUFCGVI5XCOQGMVGQNZVFLGY2RWTBIQBW2ZNLT',
    contract: 'CDAHEWKJHBOBREILPDRLCHIGTPV52UVQZWYBFVXQZAPSZVPP6BPOH4WH',
    name: 'NLT',
    org: 'unknown',
    domain: 'nolimitstellar.com',
    decimals: 7,
  },
  {
    code: 'ACT',
    issuer: 'GAHHULDPDVGB5WS5PH7BCGLJ7ZHECDBIIMKB62UPVDUOCHNFL7HX3FS7',
    contract: 'CAU7TR4L52CSCYOLOPXPJJ7T6EMEXTEE4XKRH2ASY23EFYEMU5WUFYP2',
    name: 'ACT',
    org: 'unknown',
    domain: 'authentic-payment.com',
    decimals: 7,
  },
  {
    code: 'USDZ',
    issuer: 'GAKTLPC4ZV37SSCITQ5IS5AQ4WPF4CF4VZJQPPAROSGXMYOATF5U6XPR',
    contract: 'CD2QJMIYIUTFU45LOTPXBRQMPVKTW6NZ3GZEAAO3EHIDFKCMYVN7BZMW',
    name: 'USDZ',
    org: 'unknown',
    domain: 'zeam.money',
    decimals: 7,
    isStable: true,
  },
  {
    code: 'ETH',
    issuer: 'GBVOL67TMUQBGL4TZYNMY3ZQ5WGQYFPFD5VJRWXR72VA33VFNL225PL5',
    contract: 'CDZNTXPXR2I7VFDBYBADK2DE2SSGQ3DTXT5MJDCTYUMNVFK3CWG5NVC7',
    name: 'ETH',
    org: 'unknown',
    domain: 'stellarport.io',
    decimals: 7,
  },
  {
    code: 'RMT',
    issuer: 'GDEGOXPCHXWFYY234D2YZSPEJ24BX42ESJNVHY5H7TWWQSYRN5ZKZE3N',
    contract: 'CCXTF43JPFVLDCA3AQIW6TY4T7BMTQYZX6TC2PUV735HBFGNUQQY3AWE',
    name: 'RMT',
    org: 'unknown',
    domain: 'sureremit.co',
    decimals: 7,
  },
  {
    code: 'FIDR',
    issuer: 'GBZQNUAGO4DZFWOHJ3PVXZKZ2LTSOVAMCTVM46OEMWNWTED4DFS3NAYH',
    contract: 'CDDQRIGZRK6Z6ILV4P276HL7D3P63GFW6HBA4N4YXDMFHZ2M4VZGVYRW',
    name: 'FIDR',
    org: 'unknown',
    domain: 'fixedidr.com',
    decimals: 7,
  },
  {
    code: 'GOLD',
    issuer: 'GBC5ZGK6MQU3XG5Y72SXPA7P5R5NHYT2475SNEJB2U3EQ6J56QLVGOLD',
    contract: 'CAZJNGLR7KI3BLUY5L46OJFHZEP6ERAF6DXNENKCUCTH4AIXTJNYXVGC',
    name: 'GOLD',
    org: 'unknown',
    domain: 'mintx.co',
    decimals: 7,
  },
  {
    code: 'WXT',
    issuer: 'GASBLVHS5FOABSDNW5SPPH3QRJYXY5JHA2AOA2QHH2FJLZBRXSG4SWXT',
    contract: 'CANBKHJ6QH45HLE5UT45HNEQTEWORC5THHXNDG26W5UJDDCM4G2INAKP',
    name: 'WXT',
    org: 'unknown',
    domain: 'wxt.wirexapp.com',
    decimals: 7,
  },
]
