#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../node-gyp-build@4.5.0/node_modules/node-gyp-build/build-test.js" "$@"
else
  exec node  "$basedir/../../../../../node-gyp-build@4.5.0/node_modules/node-gyp-build/build-test.js" "$@"
fi
