import type { EvmAddress } from 'sushi/evm'
import { parseAbi } from 'viem'

export const LAUNCHPAD_ADDRESS =
  '0x104F1Ab42674565EC3DF0BFEbCcC4186f72fA7ED' satisfies EvmAddress

export const LAUNCHPAD_ABI = parseAbi([
  'function launch((string name, string symbol) tokenConfig, address quoteToken, uint64 deadline) payable returns (address token, address pool, uint256 positionId)',
  'function launchAndBuy((string name, string symbol) tokenConfig, address quoteToken, uint64 deadline, (uint256 amountIn, uint256 amountOutMinimum, address recipient) initialBuy) payable returns (address token, address pool, uint256 positionId, uint256 amountOut)',
  'function launchAndBuyNative((string name, string symbol) tokenConfig, uint64 deadline, (uint256 amountIn, uint256 amountOutMinimum, address recipient) initialBuy) payable returns (address token, address pool, uint256 positionId, uint256 amountOut)',
  'function distributeFees(address token) returns (uint256 quoteCollected, uint256 tokenCollected, uint256 quoteToSushi, uint256 tokenToSushi)',
  'function launchFee() view returns (uint256)',
  'function protocolReserveBps() view returns (uint16)',
  'function defaultSushiFeeBps() view returns (uint16)',
  'function calculateStartTick(address quoteToken) view returns (int24)',
  'event TokenLaunched(address indexed creator, address indexed token, address indexed pool, address quoteToken, int24 startTick, string name, string symbol, uint16 reserveBps, uint256 reserveAmount, uint64 reserveUnlockAt, uint16 initialSushiFeeBps)',
  'error NothingToWithdraw()',
  'error UnknownToken(address token)',
  'error ZeroAddress()',
  'error InvalidQuoteToken(address quoteToken)',
  'error UnsupportedQuoteToken(address quoteToken)',
  'error InvalidPriceFeed(address priceFeed)',
  'error InvalidQuoteTokenDecimals(uint8 decimals)',
  'error InvalidPriceFeedDecimals(uint8 decimals)',
  'error InvalidPriceFeedAnswer(int256 answer)',
  'error IncompletePriceFeedRound(uint80 roundId, uint80 answeredInRound, uint256 updatedAt)',
  'error StalePriceFeedRound(uint256 updatedAt, uint256 currentTimestamp, uint256 maximumAge)',
  'error InitialPriceOutOfBounds(uint160 sqrtPriceX96)',
  'error InvalidPositionManager()',
  'error InvalidTickSpacing(int24 actualTickSpacing)',
  'error EmptyName()',
  'error EmptySymbol()',
  'error NameTooLong(uint256 length)',
  'error SymbolTooLong(uint256 length)',
  'error InsufficientLaunchFee(uint256 required, uint256 supplied)',
  'error DeadlineExpired(uint64 deadline)',
  'error NoCleanTokenAddress()',
  'error UnexpectedExistingPool(address token, address pool)',
  'error PoolCreationMismatch(address expected, address actual)',
  'error PoolConfigurationMismatch(address pool)',
  'error PoolInitializationMismatch(uint160 expected, uint160 actual)',
  'error ZeroLiquidity()',
  'error NonzeroQuoteTokenUsed(uint256 amount)',
  'error ExcessTokenConsumption(uint256 used, uint256 desired)',
  'error PositionConfigurationMismatch(uint256 positionId)',
  'error SupplyReconciliationFailure(uint256 expected, uint256 accounted)',
  'error ZeroInitialBuyAmount()',
  'error InitialBuyAmountTooLarge(uint256 amount)',
  'error InvalidInitialBuyRecipient(address recipient)',
  'error ExcessiveInitialBuyInput(uint256 maximum, uint256 required)',
  'error PartialInitialBuy(uint256 requested, uint256 consumed)',
  'error InsufficientInitialBuyOutput(uint256 minimum, uint256 actual)',
  'error InvalidNativeValue(uint256 required, uint256 supplied)',
  'error InvalidSwapCallback(address caller)',
  'error SwapCallbackNotConsumed(address pool)',
  'error InvalidSwapDeltas(int256 amount0Delta, int256 amount1Delta)',
])
