version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    commit-message:
      # Prefix all commit messages with "npm"
      prefix: 'token list'
      include: 'scope'
    labels:
      - 'tokenlist'
      # Add default Kodiak `merge.automerge_label`
      #- 'automerge'
    allow:
      - dependency-name: '@sushiswap/bentobox-sdk'
      - dependency-name: '@sushiswap/chainlink-whitelist'
      - dependency-name: '@sushiswap/core'
      - dependency-name: '@sushiswap/core-sdk'
      - dependency-name: '@sushiswap/default-token-list'
      - dependency-name: '@sushiswap/kashi-sdk'
      - dependency-name: '@sushiswap/limit-order-pair-list'
      - dependency-name: '@sushiswap/limit-order-sdk'
      - dependency-name: '@sushiswap/tines'
      - dependency-name: '@sushiswap/trident'
      - dependency-name: '@sushiswap/trident-sdk'
