packages:
  - 'apis/*'
  - 'apps/*'
  - 'config/*'
  - 'packages/*'
  - 'packages/stellar/contract-bindings/*'

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - sushi

catalog:
  "typescript": 5.9.3
  "utf-8-validate": 6.0.3
  "zod": 4.1.11

catalogs:
  web3:
    "abitype": 1.2.3
    "wagmi": 3.3.2
    "@wagmi/core": 3.2.2
    "viem": 2.55.0
    "@solana/addresses": 6.0.1
    "sushi": 7.2.1

  react:
    "next": 16.2.9
    "react": 19.2.7
    "@types/react": 19.2.17
    "react-dom": 19.2.7
    "@types/react-dom": 19.2.3
  
  ui:
    "tailwindcss": 3.4.19

  tsconfig:
    "@tsconfig/next": 2.0.1
    "@tsconfig/node24": 24.0.4
    "@tsconfig/strictest": 2.0.2
