packages:
  - 'apis/*'
  - 'apps/*'
  - 'config/*'
  - 'packages/*'

catalog:
  "typescript": 5.8.3
  "utf-8-validate": 6.0.3
  "zod": 4.1.11

catalogs:
  web3:
    "abitype": 1.1.1
    "sushi": 6.2.18
    "wagmi": 3.0.1
    "@wagmi/core": 3.0.0
    "viem": 2.40.2

  react:
    "next": 15.5.9
    "react": 19.0.1
    "@types/react": 19.0.1
    "react-dom": 19.0.1
    "@types/react-dom": 19.0.2
  
  ui:
    "tailwindcss": 3.3.2

  tsconfig:
    "@tsconfig/next": 2.0.1
    "@tsconfig/node20": 20.1.4
    "@tsconfig/strictest": 2.0.2