packages:
  - 'apis/*'
  - 'apps/*'
  - 'config/*'
  - 'packages/*'

catalog:
  "typescript": 5.8.3

catalogs:
  web3:
    "sushi": 6.0.8
    "wagmi": 2.15.6
    "@wagmi/core": 2.17.3
    "viem": 2.31.4

  react:
    "next": 15.1.4
    "react": 19.0.0
    "@types/react": 19.0.1
    "react-dom": 19.0.0
    "@types/react-dom": 19.0.2
  
  ui:
    "tailwindcss": 3.3.2

  tsconfig:
    "@tsconfig/next": 2.0.1
    "@tsconfig/node20": 20.1.4
    "@tsconfig/strictest": 2.0.2