import { ChainId } from '@sushiswap/chain'

import { OP, SUSHI, USDC } from './constants'

export const defaultQuoteCurrency = {
  [ChainId.ETHEREUM]: SUSHI[ChainId.ETHEREUM],
  [ChainId.ROPSTEN]: SUSHI[ChainId.ROPSTEN],
  [ChainId.RINKEBY]: SUSHI[ChainId.RINKEBY],
  [ChainId.GÖRLI]: SUSHI[ChainId.GÖRLI],
  [ChainId.KOVAN]: SUSHI[ChainId.KOVAN],
  [ChainId.POLYGON]: SUSHI[ChainId.POLYGON],
  // [ChainId.POLYGON_TESTNET]: SUSHI[ChainId.POLYGON_TESTNET],
  [ChainId.FANTOM]: SUSHI[ChainId.FANTOM],
  // [ChainId.FANTOM_TESTNET]: SUSHI[ChainId.FANTOM_TESTNET],
  [ChainId.GNOSIS]: SUSHI[ChainId.GNOSIS],
  [ChainId.BSC]: SUSHI[ChainId.BSC],
  // [ChainId.BSC_TESTNET]: SUSHI[ChainId.BSC_TESTNET],
  [ChainId.ARBITRUM]: SUSHI[ChainId.ARBITRUM],
  [ChainId.ARBITRUM_NOVA]: SUSHI[ChainId.ARBITRUM_NOVA],
  // [ChainId.ARBITRUM_TESTNET]: 'SUSHI',
  [ChainId.AVALANCHE]: SUSHI[ChainId.AVALANCHE],
  // [ChainId.AVALANCHE_TESTNET]: 'SUSHI',
  [ChainId.HECO]: SUSHI[ChainId.HECO],
  // [ChainId.HECO_TESTNET]: 'SUSHI',
  [ChainId.HARMONY]: SUSHI[ChainId.HARMONY],
  // [ChainId.HARMONY_TESTNET]: 'SUSHI',
  [ChainId.OKEX]: SUSHI[ChainId.OKEX],
  // [ChainId.OKEX_TESTNET]: 'SUSHI',
  [ChainId.CELO]: SUSHI[ChainId.CELO],
  // [ChainId.PALM]: SUSHI[ChainId.PALM],
  [ChainId.MOONRIVER]: SUSHI[ChainId.MOONRIVER],
  [ChainId.FUSE]: SUSHI[ChainId.FUSE],
  [ChainId.TELOS]: SUSHI[ChainId.TELOS],
  [ChainId.MOONBEAM]: SUSHI[ChainId.MOONBEAM],
  [ChainId.OPTIMISM]: OP[ChainId.OPTIMISM],
  [ChainId.KAVA]: SUSHI[ChainId.KAVA],
  [ChainId.METIS]: SUSHI[ChainId.METIS],
  [ChainId.BOBA]: USDC[ChainId.BOBA],
  [ChainId.BOBA_AVAX]: USDC[ChainId.BOBA_AVAX],
  [ChainId.BOBA_BNB]: USDC[ChainId.BOBA_BNB],
  // [ChainId.BTTC]: USDT[ChainId.BTTC],
  // [ChainId.SEPOLIA]: USDT[ChainId.SEPOLIA],
} as const
