/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TickMathMockInterface extends utils.Interface {
  functions: {
    "getSqrtRatioAtTick(int24)": FunctionFragment;
    "getTickAtSqrtRatio(uint160)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getSqrtRatioAtTick",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTickAtSqrtRatio",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getSqrtRatioAtTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTickAtSqrtRatio",
    data: BytesLike
  ): Result;

  events: {};
}

export interface TickMathMock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TickMathMockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getSqrtRatioAtTick(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTickAtSqrtRatio(
      sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;
  };

  getSqrtRatioAtTick(
    tick: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTickAtSqrtRatio(
    sqrtPriceX96: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  callStatic: {
    getSqrtRatioAtTick(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTickAtSqrtRatio(
      sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {};

  estimateGas: {
    getSqrtRatioAtTick(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTickAtSqrtRatio(
      sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getSqrtRatioAtTick(
      tick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTickAtSqrtRatio(
      sqrtPriceX96: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
