import type { IBuildManifest, IPreRenderManifest, IRoutesManifest, INextManifest } from '../interface.js';
export declare const sampleBuildManifest: IBuildManifest;
export declare const samplePreRenderManifest: IPreRenderManifest;
export declare const sampleManifest: INextManifest;
export declare const sampleI18nBuildManifest: IBuildManifest;
export declare const sampleI18nPreRenderManifest: IPreRenderManifest;
export declare const sampleRenderManifest: IRoutesManifest;
export declare const sampleI18nManifest: INextManifest;
export declare const sampleNotFoundRoutesBuildManifest: IBuildManifest;
export declare const sampleNotFoundRoutesPreRenderManifest: IPreRenderManifest;
export declare const sampleNotFoundRoutesRenderManifest: IRoutesManifest;
export declare const sampleNotFoundRoutesManifest: INextManifest;
