sources:
  - name: Kashi
    handler:
      graphql:
        endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:olastenberg/kashi-arbitrum}

additionalTypeDefs: |
  extend type KashiPair {
    chainId: BigInt!
    chainName: String!
  }
  extend type Query {
    crossChainKashiPair(id: String!, now: Int!, chainId: BigInt!): KashiPair!
    crossChainKashiPairs(first: Int!, orderBy: KashiPair_orderBy, orderDirection: OrderDirection, where: KashiPair_filter, chainIds: [BigInt!]!): [KashiPair!]!
  }


additionalResolvers:
  - ./resolvers.ts

documents:
  - ./query.graphql

codegen:
  contextType: 'MeshContext & { chainId: string; chainName: string; subgraphName: string; subgraphHost: string }'
