sources:
  - name: Kashi
    handler:
      graphql:
        endpoint: https://{context.subgraphHost:api.thegraph.com/subgraphs/name}/{context.subgraphName:matthewlilley/kashi-ethereum}

additionalTypeDefs: |
  extend type KashiPair {
    chainId: BigInt!
    chainName: String!
  }
  type Dashboard {
    lend: [KashiPair!]!
    borrow: [KashiPair!]!
  }
  type Datapoint {
    x: [BigInt!]!
    y: [BigInt!]!
  }
  extend type Query {
    dashboard(
      first: Int, 
      skip: Int, 
      orderBy: KashiPair_orderBy, 
      orderDirection: OrderDirection, 
      where: KashiPair_filter, 
      chainIds: [BigInt!]!
    ): Dashboard!
    datapoints(
      first: Int, 
      skip: Int, 
      orderBy: KashiPair_orderBy, 
      orderDirection: OrderDirection, 
      where: KashiPair_filter, 
      chainIds: [BigInt!]!
    ): Datapoint!
    pair(
      id: String!, 
      now: Int!, 
      chainId: BigInt!
    ): KashiPair!
    pairs(
      first: Int, 
      skip: Int, 
      orderBy: KashiPair_orderBy,
      orderDirection: OrderDirection,
      where: KashiPair_filter,
      chainIds: [BigInt!]!
    ): [KashiPair!]!
  }


additionalResolvers:
  - ./resolvers

documents:
  - ./query.graphql

codegen:
  contextType: 'MeshContext & { chainId: string; chainName: string; subgraphName: string; subgraphHost: string }'
