/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IFauceteerInterface extends ethers.utils.Interface {
  functions: {
    "drip(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "drip", values: [string]): string;

  decodeFunctionResult(functionFragment: "drip", data: BytesLike): Result;

  events: {};
}

export class IFauceteer extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IFauceteerInterface;

  functions: {
    drip(token: string, overrides?: Overrides): Promise<ContractTransaction>;

    "drip(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  drip(token: string, overrides?: Overrides): Promise<ContractTransaction>;

  "drip(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    drip(token: string, overrides?: CallOverrides): Promise<void>;

    "drip(address)"(token: string, overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    drip(token: string, overrides?: Overrides): Promise<BigNumber>;

    "drip(address)"(token: string, overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    drip(token: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "drip(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
