"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.forwardArgsToSelectionSet = exports.createMergedTypeResolver = exports.stitchSchemas = void 0;
const tslib_1 = require("tslib");
var stitchSchemas_js_1 = require("./stitchSchemas.js");
Object.defineProperty(exports, "stitchSchemas", { enumerable: true, get: function () { return stitchSchemas_js_1.stitchSchemas; } });
var createMergedTypeResolver_js_1 = require("./createMergedTypeResolver.js");
Object.defineProperty(exports, "createMergedTypeResolver", { enumerable: true, get: function () { return createMergedTypeResolver_js_1.createMergedTypeResolver; } });
var selectionSetArgs_js_1 = require("./selectionSetArgs.js");
Object.defineProperty(exports, "forwardArgsToSelectionSet", { enumerable: true, get: function () { return selectionSetArgs_js_1.forwardArgsToSelectionSet; } });
tslib_1.__exportStar(require("./subschemaConfigTransforms/index.js"), exports);
tslib_1.__exportStar(require("./types.js"), exports);
tslib_1.__exportStar(require("./relay.js"), exports);
