/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITridentNFT, ITridentNFTInterface } from "../ITridentNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITridentNFT__factory {
  static readonly abi = _abi;
  static createInterface(): ITridentNFTInterface {
    return new utils.Interface(_abi) as ITridentNFTInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITridentNFT {
    return new Contract(address, _abi, signerOrProvider) as ITridentNFT;
  }
}
