/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IZkSyncInterface extends ethers.utils.Interface {
  functions: {
    "activatePriorityMode(uint32)": FunctionFragment;
    "approveEmergencyDiamondCutAsSecurityCouncilMember(bytes32)": FunctionFragment;
    "cancelDiamondCutProposal()": FunctionFragment;
    "changeGovernor(address)": FunctionFragment;
    "commitBlocks(tuple,tuple[])": FunctionFragment;
    "emergencyFreezeDiamond()": FunctionFragment;
    "executeBlocks(tuple[])": FunctionFragment;
    "executeDiamondCutProposal(tuple)": FunctionFragment;
    "facetAddress(bytes4)": FunctionFragment;
    "facetAddresses()": FunctionFragment;
    "facetFunctionSelectors(address)": FunctionFragment;
    "facets()": FunctionFragment;
    "facetsExtended()": FunctionFragment;
    "getGovernor()": FunctionFragment;
    "getTotalBlocksCommitted()": FunctionFragment;
    "getTotalBlocksExecuted()": FunctionFragment;
    "getTotalBlocksVerified()": FunctionFragment;
    "getTotalPriorityRequests()": FunctionFragment;
    "getVerifier()": FunctionFragment;
    "isFunctionFreezable(bytes4)": FunctionFragment;
    "isValidator(address)": FunctionFragment;
    "l2LogsRootHash(uint32)": FunctionFragment;
    "l2TransactionBaseCost(uint256,uint256,uint32,uint8)": FunctionFragment;
    "movePriorityOpsFromBufferToMainQueue(uint256,uint8)": FunctionFragment;
    "placeBidForBlocksProcessingAuction(uint112,uint8)": FunctionFragment;
    "proposeDiamondCut(tuple[],address)": FunctionFragment;
    "proveBlocks(tuple[],tuple)": FunctionFragment;
    "proveL2LogInclusion(uint32,uint256,tuple,bytes32[])": FunctionFragment;
    "proveL2MessageInclusion(uint32,uint256,tuple,bytes32[])": FunctionFragment;
    "requestL2Transaction(address,bytes,uint256,bytes[],uint8)": FunctionFragment;
    "revertBlocks(uint32)": FunctionFragment;
    "serializeL2Transaction(uint64,uint256,address,address,bytes,uint256,bytes[])": FunctionFragment;
    "setValidator(address,bool)": FunctionFragment;
    "unfreezeDiamond()": FunctionFragment;
    "updatePriorityModeSubEpoch()": FunctionFragment;
    "withdrawAuctionBid(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "activatePriorityMode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveEmergencyDiamondCutAsSecurityCouncilMember",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelDiamondCutProposal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeGovernor",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "commitBlocks",
    values: [
      {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      },
      {
        newStateRoot: BytesLike;
        blockNumber: BigNumberish;
        feeAccount: string;
        timestamp: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        numberOfLayer2Txs: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        l2Logs: BytesLike;
        l2ArbitraryLengthMessages: BytesLike[];
        deployedContracts: BytesLike;
        storageChanges: BytesLike;
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyFreezeDiamond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeBlocks",
    values: [
      {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "executeDiamondCutProposal",
    values: [
      {
        facetCuts: {
          facet: string;
          action: BigNumberish;
          isFreezable: boolean;
          selectors: BytesLike[];
        }[];
        initAddress: string;
        initCalldata: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "facetAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "facetAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "facetFunctionSelectors",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "facets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "facetsExtended",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGovernor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalBlocksCommitted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalBlocksExecuted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalBlocksVerified",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPriorityRequests",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isFunctionFreezable",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isValidator", values: [string]): string;
  encodeFunctionData(
    functionFragment: "l2LogsRootHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "l2TransactionBaseCost",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "movePriorityOpsFromBufferToMainQueue",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "placeBidForBlocksProcessingAuction",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeDiamondCut",
    values: [
      {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[],
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proveBlocks",
    values: [
      {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      {
        recursiveInput: BigNumberish[];
        proof: BigNumberish[];
        commitments: BigNumberish[];
        vkIndexes: BigNumberish[];
        subproofsLimbs: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proveL2LogInclusion",
    values: [
      BigNumberish,
      BigNumberish,
      { sender: string; key: BytesLike; value: BytesLike },
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "proveL2MessageInclusion",
    values: [
      BigNumberish,
      BigNumberish,
      { sender: string; data: BytesLike },
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestL2Transaction",
    values: [string, BytesLike, BigNumberish, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revertBlocks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "serializeL2Transaction",
    values: [
      BigNumberish,
      BigNumberish,
      string,
      string,
      BytesLike,
      BigNumberish,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setValidator",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezeDiamond",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePriorityModeSubEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawAuctionBid",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "activatePriorityMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveEmergencyDiamondCutAsSecurityCouncilMember",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelDiamondCutProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyFreezeDiamond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeDiamondCutProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "facetAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "facetAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "facetFunctionSelectors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "facets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "facetsExtended",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGovernor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBlocksCommitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBlocksExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalBlocksVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPriorityRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFunctionFreezable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2LogsRootHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "l2TransactionBaseCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "movePriorityOpsFromBufferToMainQueue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "placeBidForBlocksProcessingAuction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeDiamondCut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proveBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proveL2LogInclusion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proveL2MessageInclusion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestL2Transaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revertBlocks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serializeL2Transaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezeDiamond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePriorityModeSubEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawAuctionBid",
    data: BytesLike
  ): Result;

  events: {
    "BlockCommit(uint32)": EventFragment;
    "BlockExecution(uint32)": EventFragment;
    "BlocksRevert(uint32,uint32)": EventFragment;
    "DiamondCutProposal(tuple[],address)": EventFragment;
    "DiamondCutProposalCancelation()": EventFragment;
    "DiamondCutProposalExecution(tuple)": EventFragment;
    "EmergencyDiamondCutApproved(address)": EventFragment;
    "EmergencyFreeze()": EventFragment;
    "MovePriorityOperationsFromBufferToHeap(uint32,uint64[],uint8)": EventFragment;
    "NewGovernor(address)": EventFragment;
    "NewPriorityModeAuctionBid(uint8,address,uint96,uint256)": EventFragment;
    "NewPriorityModeSubEpoch(uint8,uint128)": EventFragment;
    "NewPriorityRequest(uint64,bytes32,uint64,tuple,bytes[])": EventFragment;
    "PriorityModeActivated()": EventFragment;
    "Unfreeze()": EventFragment;
    "ValidatorStatusUpdate(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BlockCommit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlockExecution"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BlocksRevert"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DiamondCutProposal"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DiamondCutProposalCancelation"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DiamondCutProposalExecution"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "EmergencyDiamondCutApproved"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EmergencyFreeze"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "MovePriorityOperationsFromBufferToHeap"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewGovernor"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewPriorityModeAuctionBid"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewPriorityModeSubEpoch"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewPriorityRequest"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PriorityModeActivated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unfreeze"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ValidatorStatusUpdate"): EventFragment;
}

export class IZkSync extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IZkSyncInterface;

  functions: {
    activatePriorityMode(
      _ethExpirationBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "activatePriorityMode(uint32)"(
      _ethExpirationBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    approveEmergencyDiamondCutAsSecurityCouncilMember(
      _diamondCutHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approveEmergencyDiamondCutAsSecurityCouncilMember(bytes32)"(
      _diamondCutHash: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    cancelDiamondCutProposal(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "cancelDiamondCutProposal()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    changeGovernor(
      _newGovernor: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "changeGovernor(address)"(
      _newGovernor: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    commitBlocks(
      _lastCommittedBlockData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      },
      _newBlocksData: {
        newStateRoot: BytesLike;
        blockNumber: BigNumberish;
        feeAccount: string;
        timestamp: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        numberOfLayer2Txs: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        l2Logs: BytesLike;
        l2ArbitraryLengthMessages: BytesLike[];
        deployedContracts: BytesLike;
        storageChanges: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "commitBlocks((uint32,uint16,uint224,bytes32,bytes32,uint256,bytes32,bytes32),tuple[])"(
      _lastCommittedBlockData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      },
      _newBlocksData: {
        newStateRoot: BytesLike;
        blockNumber: BigNumberish;
        feeAccount: string;
        timestamp: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        numberOfLayer2Txs: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        l2Logs: BytesLike;
        l2ArbitraryLengthMessages: BytesLike[];
        deployedContracts: BytesLike;
        storageChanges: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    emergencyFreezeDiamond(overrides?: Overrides): Promise<ContractTransaction>;

    "emergencyFreezeDiamond()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    executeBlocks(
      _blocksData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeBlocks(tuple[])"(
      _blocksData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    executeDiamondCutProposal(
      _diamondCut: {
        facetCuts: {
          facet: string;
          action: BigNumberish;
          isFreezable: boolean;
          selectors: BytesLike[];
        }[];
        initAddress: string;
        initCalldata: BytesLike;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "executeDiamondCutProposal((tuple[],address,bytes))"(
      _diamondCut: {
        facetCuts: {
          facet: string;
          action: BigNumberish;
          isFreezable: boolean;
          selectors: BytesLike[];
        }[];
        initAddress: string;
        initCalldata: BytesLike;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    facetAddress(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      facet: string;
      0: string;
    }>;

    "facetAddress(bytes4)"(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      facet: string;
      0: string;
    }>;

    facetAddresses(overrides?: CallOverrides): Promise<{
      facets: string[];
      0: string[];
    }>;

    "facetAddresses()"(overrides?: CallOverrides): Promise<{
      facets: string[];
      0: string[];
    }>;

    facetFunctionSelectors(
      _facet: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    "facetFunctionSelectors(address)"(
      _facet: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string[];
    }>;

    facets(overrides?: CallOverrides): Promise<{
      0: { addr: string; selectors: string[]; 0: string; 1: string[] }[];
    }>;

    "facets()"(overrides?: CallOverrides): Promise<{
      0: { addr: string; selectors: string[]; 0: string; 1: string[] }[];
    }>;

    facetsExtended(overrides?: CallOverrides): Promise<{
      0: {
        addr: string;
        selectors: {
          selector: string;
          isFreezable: boolean;
          0: string;
          1: boolean;
        }[];
        0: string;
        1: { selector: string; isFreezable: boolean; 0: string; 1: boolean }[];
      }[];
    }>;

    "facetsExtended()"(overrides?: CallOverrides): Promise<{
      0: {
        addr: string;
        selectors: {
          selector: string;
          isFreezable: boolean;
          0: string;
          1: boolean;
        }[];
        0: string;
        1: { selector: string; isFreezable: boolean; 0: string; 1: boolean }[];
      }[];
    }>;

    getGovernor(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "getGovernor()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    getTotalBlocksCommitted(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    "getTotalBlocksCommitted()"(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    getTotalBlocksExecuted(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    "getTotalBlocksExecuted()"(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    getTotalBlocksVerified(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    "getTotalBlocksVerified()"(overrides?: CallOverrides): Promise<{
      0: number;
    }>;

    getTotalPriorityRequests(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "getTotalPriorityRequests()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    getVerifier(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "getVerifier()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    isFunctionFreezable(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isFunctionFreezable(bytes4)"(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    isValidator(
      _address: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isValidator(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    l2LogsRootHash(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      hash: string;
      0: string;
    }>;

    "l2LogsRootHash(uint32)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      hash: string;
      0: string;
    }>;

    l2TransactionBaseCost(
      _gasPrice: BigNumberish,
      _ergsLimit: BigNumberish,
      _calldataLength: BigNumberish,
      _queueType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "l2TransactionBaseCost(uint256,uint256,uint32,uint8)"(
      _gasPrice: BigNumberish,
      _ergsLimit: BigNumberish,
      _calldataLength: BigNumberish,
      _queueType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    movePriorityOpsFromBufferToMainQueue(
      _nOpsToMove: BigNumberish,
      _opTree: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "movePriorityOpsFromBufferToMainQueue(uint256,uint8)"(
      _nOpsToMove: BigNumberish,
      _opTree: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    placeBidForBlocksProcessingAuction(
      _complexityRoot: BigNumberish,
      _opTree: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "placeBidForBlocksProcessingAuction(uint112,uint8)"(
      _complexityRoot: BigNumberish,
      _opTree: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    proposeDiamondCut(
      _facetCuts: {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[],
      _initAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "proposeDiamondCut(tuple[],address)"(
      _facetCuts: {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[],
      _initAddress: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    proveBlocks(
      _committedBlocks: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      _proof: {
        recursiveInput: BigNumberish[];
        proof: BigNumberish[];
        commitments: BigNumberish[];
        vkIndexes: BigNumberish[];
        subproofsLimbs: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "proveBlocks(tuple[],(uint256[],uint256[],uint256[],uint8[],uint256[16]))"(
      _committedBlocks: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      _proof: {
        recursiveInput: BigNumberish[];
        proof: BigNumberish[];
        commitments: BigNumberish[];
        vkIndexes: BigNumberish[];
        subproofsLimbs: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    proveL2LogInclusion(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _log: { sender: string; key: BytesLike; value: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "proveL2LogInclusion(uint32,uint256,(address,bytes32,bytes32),bytes32[])"(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _log: { sender: string; key: BytesLike; value: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    proveL2MessageInclusion(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _message: { sender: string; data: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "proveL2MessageInclusion(uint32,uint256,(address,bytes),bytes32[])"(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _message: { sender: string; data: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    requestL2Transaction(
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      _queueType: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "requestL2Transaction(address,bytes,uint256,bytes[],uint8)"(
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      _queueType: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    revertBlocks(
      _blocksToRevert: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revertBlocks(uint32)"(
      _blocksToRevert: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    serializeL2Transaction(
      _txId: BigNumberish,
      _layer2Tip: BigNumberish,
      _sender: string,
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      0: {
        txType: BigNumber;
        from: BigNumber;
        to: BigNumber;
        feeToken: BigNumber;
        ergsLimit: BigNumber;
        ergsPerPubdataByteLimit: BigNumber;
        ergsPrice: BigNumber;
        reserved: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ];
        data: string;
        signature: string;
        reservedDynamic: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: BigNumber;
        6: BigNumber;
        7: [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber];
        8: string;
        9: string;
        10: string;
      };
    }>;

    "serializeL2Transaction(uint64,uint256,address,address,bytes,uint256,bytes[])"(
      _txId: BigNumberish,
      _layer2Tip: BigNumberish,
      _sender: string,
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      0: {
        txType: BigNumber;
        from: BigNumber;
        to: BigNumber;
        feeToken: BigNumber;
        ergsLimit: BigNumber;
        ergsPerPubdataByteLimit: BigNumber;
        ergsPrice: BigNumber;
        reserved: [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ];
        data: string;
        signature: string;
        reservedDynamic: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: BigNumber;
        6: BigNumber;
        7: [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber];
        8: string;
        9: string;
        10: string;
      };
    }>;

    setValidator(
      _validator: string,
      _active: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setValidator(address,bool)"(
      _validator: string,
      _active: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    unfreezeDiamond(overrides?: Overrides): Promise<ContractTransaction>;

    "unfreezeDiamond()"(overrides?: Overrides): Promise<ContractTransaction>;

    updatePriorityModeSubEpoch(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updatePriorityModeSubEpoch()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    withdrawAuctionBid(
      _recipient: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "withdrawAuctionBid(address)"(
      _recipient: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  activatePriorityMode(
    _ethExpirationBlock: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "activatePriorityMode(uint32)"(
    _ethExpirationBlock: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  approveEmergencyDiamondCutAsSecurityCouncilMember(
    _diamondCutHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approveEmergencyDiamondCutAsSecurityCouncilMember(bytes32)"(
    _diamondCutHash: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  cancelDiamondCutProposal(overrides?: Overrides): Promise<ContractTransaction>;

  "cancelDiamondCutProposal()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  changeGovernor(
    _newGovernor: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "changeGovernor(address)"(
    _newGovernor: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  commitBlocks(
    _lastCommittedBlockData: {
      blockNumber: BigNumberish;
      numberOfLayer1Txs: BigNumberish;
      priorityOperationsComplexity: BigNumberish;
      priorityOperationsHash: BytesLike;
      l2LogsTreeRoot: BytesLike;
      timestamp: BigNumberish;
      stateRoot: BytesLike;
      commitment: BytesLike;
    },
    _newBlocksData: {
      newStateRoot: BytesLike;
      blockNumber: BigNumberish;
      feeAccount: string;
      timestamp: BigNumberish;
      priorityOperationsComplexity: BigNumberish;
      numberOfLayer1Txs: BigNumberish;
      numberOfLayer2Txs: BigNumberish;
      priorityOperationsHash: BytesLike;
      l2LogsTreeRoot: BytesLike;
      l2Logs: BytesLike;
      l2ArbitraryLengthMessages: BytesLike[];
      deployedContracts: BytesLike;
      storageChanges: BytesLike;
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "commitBlocks((uint32,uint16,uint224,bytes32,bytes32,uint256,bytes32,bytes32),tuple[])"(
    _lastCommittedBlockData: {
      blockNumber: BigNumberish;
      numberOfLayer1Txs: BigNumberish;
      priorityOperationsComplexity: BigNumberish;
      priorityOperationsHash: BytesLike;
      l2LogsTreeRoot: BytesLike;
      timestamp: BigNumberish;
      stateRoot: BytesLike;
      commitment: BytesLike;
    },
    _newBlocksData: {
      newStateRoot: BytesLike;
      blockNumber: BigNumberish;
      feeAccount: string;
      timestamp: BigNumberish;
      priorityOperationsComplexity: BigNumberish;
      numberOfLayer1Txs: BigNumberish;
      numberOfLayer2Txs: BigNumberish;
      priorityOperationsHash: BytesLike;
      l2LogsTreeRoot: BytesLike;
      l2Logs: BytesLike;
      l2ArbitraryLengthMessages: BytesLike[];
      deployedContracts: BytesLike;
      storageChanges: BytesLike;
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  emergencyFreezeDiamond(overrides?: Overrides): Promise<ContractTransaction>;

  "emergencyFreezeDiamond()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  executeBlocks(
    _blocksData: {
      blockNumber: BigNumberish;
      numberOfLayer1Txs: BigNumberish;
      priorityOperationsComplexity: BigNumberish;
      priorityOperationsHash: BytesLike;
      l2LogsTreeRoot: BytesLike;
      timestamp: BigNumberish;
      stateRoot: BytesLike;
      commitment: BytesLike;
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeBlocks(tuple[])"(
    _blocksData: {
      blockNumber: BigNumberish;
      numberOfLayer1Txs: BigNumberish;
      priorityOperationsComplexity: BigNumberish;
      priorityOperationsHash: BytesLike;
      l2LogsTreeRoot: BytesLike;
      timestamp: BigNumberish;
      stateRoot: BytesLike;
      commitment: BytesLike;
    }[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  executeDiamondCutProposal(
    _diamondCut: {
      facetCuts: {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[];
      initAddress: string;
      initCalldata: BytesLike;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "executeDiamondCutProposal((tuple[],address,bytes))"(
    _diamondCut: {
      facetCuts: {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[];
      initAddress: string;
      initCalldata: BytesLike;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  facetAddress(
    _selector: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  "facetAddress(bytes4)"(
    _selector: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  facetAddresses(overrides?: CallOverrides): Promise<string[]>;

  "facetAddresses()"(overrides?: CallOverrides): Promise<string[]>;

  facetFunctionSelectors(
    _facet: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  "facetFunctionSelectors(address)"(
    _facet: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  facets(
    overrides?: CallOverrides
  ): Promise<{ addr: string; selectors: string[]; 0: string; 1: string[] }[]>;

  "facets()"(
    overrides?: CallOverrides
  ): Promise<{ addr: string; selectors: string[]; 0: string; 1: string[] }[]>;

  facetsExtended(
    overrides?: CallOverrides
  ): Promise<
    {
      addr: string;
      selectors: {
        selector: string;
        isFreezable: boolean;
        0: string;
        1: boolean;
      }[];
      0: string;
      1: { selector: string; isFreezable: boolean; 0: string; 1: boolean }[];
    }[]
  >;

  "facetsExtended()"(
    overrides?: CallOverrides
  ): Promise<
    {
      addr: string;
      selectors: {
        selector: string;
        isFreezable: boolean;
        0: string;
        1: boolean;
      }[];
      0: string;
      1: { selector: string; isFreezable: boolean; 0: string; 1: boolean }[];
    }[]
  >;

  getGovernor(overrides?: CallOverrides): Promise<string>;

  "getGovernor()"(overrides?: CallOverrides): Promise<string>;

  getTotalBlocksCommitted(overrides?: CallOverrides): Promise<number>;

  "getTotalBlocksCommitted()"(overrides?: CallOverrides): Promise<number>;

  getTotalBlocksExecuted(overrides?: CallOverrides): Promise<number>;

  "getTotalBlocksExecuted()"(overrides?: CallOverrides): Promise<number>;

  getTotalBlocksVerified(overrides?: CallOverrides): Promise<number>;

  "getTotalBlocksVerified()"(overrides?: CallOverrides): Promise<number>;

  getTotalPriorityRequests(overrides?: CallOverrides): Promise<BigNumber>;

  "getTotalPriorityRequests()"(overrides?: CallOverrides): Promise<BigNumber>;

  getVerifier(overrides?: CallOverrides): Promise<string>;

  "getVerifier()"(overrides?: CallOverrides): Promise<string>;

  isFunctionFreezable(
    _selector: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isFunctionFreezable(bytes4)"(
    _selector: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isValidator(_address: string, overrides?: CallOverrides): Promise<boolean>;

  "isValidator(address)"(
    _address: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  l2LogsRootHash(
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "l2LogsRootHash(uint32)"(
    blockNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  l2TransactionBaseCost(
    _gasPrice: BigNumberish,
    _ergsLimit: BigNumberish,
    _calldataLength: BigNumberish,
    _queueType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "l2TransactionBaseCost(uint256,uint256,uint32,uint8)"(
    _gasPrice: BigNumberish,
    _ergsLimit: BigNumberish,
    _calldataLength: BigNumberish,
    _queueType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  movePriorityOpsFromBufferToMainQueue(
    _nOpsToMove: BigNumberish,
    _opTree: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "movePriorityOpsFromBufferToMainQueue(uint256,uint8)"(
    _nOpsToMove: BigNumberish,
    _opTree: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  placeBidForBlocksProcessingAuction(
    _complexityRoot: BigNumberish,
    _opTree: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "placeBidForBlocksProcessingAuction(uint112,uint8)"(
    _complexityRoot: BigNumberish,
    _opTree: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  proposeDiamondCut(
    _facetCuts: {
      facet: string;
      action: BigNumberish;
      isFreezable: boolean;
      selectors: BytesLike[];
    }[],
    _initAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "proposeDiamondCut(tuple[],address)"(
    _facetCuts: {
      facet: string;
      action: BigNumberish;
      isFreezable: boolean;
      selectors: BytesLike[];
    }[],
    _initAddress: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  proveBlocks(
    _committedBlocks: {
      blockNumber: BigNumberish;
      numberOfLayer1Txs: BigNumberish;
      priorityOperationsComplexity: BigNumberish;
      priorityOperationsHash: BytesLike;
      l2LogsTreeRoot: BytesLike;
      timestamp: BigNumberish;
      stateRoot: BytesLike;
      commitment: BytesLike;
    }[],
    _proof: {
      recursiveInput: BigNumberish[];
      proof: BigNumberish[];
      commitments: BigNumberish[];
      vkIndexes: BigNumberish[];
      subproofsLimbs: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ];
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "proveBlocks(tuple[],(uint256[],uint256[],uint256[],uint8[],uint256[16]))"(
    _committedBlocks: {
      blockNumber: BigNumberish;
      numberOfLayer1Txs: BigNumberish;
      priorityOperationsComplexity: BigNumberish;
      priorityOperationsHash: BytesLike;
      l2LogsTreeRoot: BytesLike;
      timestamp: BigNumberish;
      stateRoot: BytesLike;
      commitment: BytesLike;
    }[],
    _proof: {
      recursiveInput: BigNumberish[];
      proof: BigNumberish[];
      commitments: BigNumberish[];
      vkIndexes: BigNumberish[];
      subproofsLimbs: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ];
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  proveL2LogInclusion(
    _blockNumber: BigNumberish,
    _index: BigNumberish,
    _log: { sender: string; key: BytesLike; value: BytesLike },
    _proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  "proveL2LogInclusion(uint32,uint256,(address,bytes32,bytes32),bytes32[])"(
    _blockNumber: BigNumberish,
    _index: BigNumberish,
    _log: { sender: string; key: BytesLike; value: BytesLike },
    _proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  proveL2MessageInclusion(
    _blockNumber: BigNumberish,
    _index: BigNumberish,
    _message: { sender: string; data: BytesLike },
    _proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  "proveL2MessageInclusion(uint32,uint256,(address,bytes),bytes32[])"(
    _blockNumber: BigNumberish,
    _index: BigNumberish,
    _message: { sender: string; data: BytesLike },
    _proof: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  requestL2Transaction(
    _contractAddressL2: string,
    _calldata: BytesLike,
    _ergsLimit: BigNumberish,
    _factoryDeps: BytesLike[],
    _queueType: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "requestL2Transaction(address,bytes,uint256,bytes[],uint8)"(
    _contractAddressL2: string,
    _calldata: BytesLike,
    _ergsLimit: BigNumberish,
    _factoryDeps: BytesLike[],
    _queueType: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  revertBlocks(
    _blocksToRevert: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revertBlocks(uint32)"(
    _blocksToRevert: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  serializeL2Transaction(
    _txId: BigNumberish,
    _layer2Tip: BigNumberish,
    _sender: string,
    _contractAddressL2: string,
    _calldata: BytesLike,
    _ergsLimit: BigNumberish,
    _factoryDeps: BytesLike[],
    overrides?: CallOverrides
  ): Promise<{
    txType: BigNumber;
    from: BigNumber;
    to: BigNumber;
    feeToken: BigNumber;
    ergsLimit: BigNumber;
    ergsPerPubdataByteLimit: BigNumber;
    ergsPrice: BigNumber;
    reserved: [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ];
    data: string;
    signature: string;
    reservedDynamic: string;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: BigNumber;
    7: [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber];
    8: string;
    9: string;
    10: string;
  }>;

  "serializeL2Transaction(uint64,uint256,address,address,bytes,uint256,bytes[])"(
    _txId: BigNumberish,
    _layer2Tip: BigNumberish,
    _sender: string,
    _contractAddressL2: string,
    _calldata: BytesLike,
    _ergsLimit: BigNumberish,
    _factoryDeps: BytesLike[],
    overrides?: CallOverrides
  ): Promise<{
    txType: BigNumber;
    from: BigNumber;
    to: BigNumber;
    feeToken: BigNumber;
    ergsLimit: BigNumber;
    ergsPerPubdataByteLimit: BigNumber;
    ergsPrice: BigNumber;
    reserved: [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ];
    data: string;
    signature: string;
    reservedDynamic: string;
    0: BigNumber;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: BigNumber;
    6: BigNumber;
    7: [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber];
    8: string;
    9: string;
    10: string;
  }>;

  setValidator(
    _validator: string,
    _active: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setValidator(address,bool)"(
    _validator: string,
    _active: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  unfreezeDiamond(overrides?: Overrides): Promise<ContractTransaction>;

  "unfreezeDiamond()"(overrides?: Overrides): Promise<ContractTransaction>;

  updatePriorityModeSubEpoch(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updatePriorityModeSubEpoch()"(
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  withdrawAuctionBid(
    _recipient: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "withdrawAuctionBid(address)"(
    _recipient: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    activatePriorityMode(
      _ethExpirationBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "activatePriorityMode(uint32)"(
      _ethExpirationBlock: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    approveEmergencyDiamondCutAsSecurityCouncilMember(
      _diamondCutHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "approveEmergencyDiamondCutAsSecurityCouncilMember(bytes32)"(
      _diamondCutHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    cancelDiamondCutProposal(overrides?: CallOverrides): Promise<void>;

    "cancelDiamondCutProposal()"(overrides?: CallOverrides): Promise<void>;

    changeGovernor(
      _newGovernor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "changeGovernor(address)"(
      _newGovernor: string,
      overrides?: CallOverrides
    ): Promise<void>;

    commitBlocks(
      _lastCommittedBlockData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      },
      _newBlocksData: {
        newStateRoot: BytesLike;
        blockNumber: BigNumberish;
        feeAccount: string;
        timestamp: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        numberOfLayer2Txs: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        l2Logs: BytesLike;
        l2ArbitraryLengthMessages: BytesLike[];
        deployedContracts: BytesLike;
        storageChanges: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "commitBlocks((uint32,uint16,uint224,bytes32,bytes32,uint256,bytes32,bytes32),tuple[])"(
      _lastCommittedBlockData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      },
      _newBlocksData: {
        newStateRoot: BytesLike;
        blockNumber: BigNumberish;
        feeAccount: string;
        timestamp: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        numberOfLayer2Txs: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        l2Logs: BytesLike;
        l2ArbitraryLengthMessages: BytesLike[];
        deployedContracts: BytesLike;
        storageChanges: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    emergencyFreezeDiamond(overrides?: CallOverrides): Promise<void>;

    "emergencyFreezeDiamond()"(overrides?: CallOverrides): Promise<void>;

    executeBlocks(
      _blocksData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    "executeBlocks(tuple[])"(
      _blocksData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    executeDiamondCutProposal(
      _diamondCut: {
        facetCuts: {
          facet: string;
          action: BigNumberish;
          isFreezable: boolean;
          selectors: BytesLike[];
        }[];
        initAddress: string;
        initCalldata: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "executeDiamondCutProposal((tuple[],address,bytes))"(
      _diamondCut: {
        facetCuts: {
          facet: string;
          action: BigNumberish;
          isFreezable: boolean;
          selectors: BytesLike[];
        }[];
        initAddress: string;
        initCalldata: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    facetAddress(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    "facetAddress(bytes4)"(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    facetAddresses(overrides?: CallOverrides): Promise<string[]>;

    "facetAddresses()"(overrides?: CallOverrides): Promise<string[]>;

    facetFunctionSelectors(
      _facet: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    "facetFunctionSelectors(address)"(
      _facet: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    facets(
      overrides?: CallOverrides
    ): Promise<{ addr: string; selectors: string[]; 0: string; 1: string[] }[]>;

    "facets()"(
      overrides?: CallOverrides
    ): Promise<{ addr: string; selectors: string[]; 0: string; 1: string[] }[]>;

    facetsExtended(
      overrides?: CallOverrides
    ): Promise<
      {
        addr: string;
        selectors: {
          selector: string;
          isFreezable: boolean;
          0: string;
          1: boolean;
        }[];
        0: string;
        1: { selector: string; isFreezable: boolean; 0: string; 1: boolean }[];
      }[]
    >;

    "facetsExtended()"(
      overrides?: CallOverrides
    ): Promise<
      {
        addr: string;
        selectors: {
          selector: string;
          isFreezable: boolean;
          0: string;
          1: boolean;
        }[];
        0: string;
        1: { selector: string; isFreezable: boolean; 0: string; 1: boolean }[];
      }[]
    >;

    getGovernor(overrides?: CallOverrides): Promise<string>;

    "getGovernor()"(overrides?: CallOverrides): Promise<string>;

    getTotalBlocksCommitted(overrides?: CallOverrides): Promise<number>;

    "getTotalBlocksCommitted()"(overrides?: CallOverrides): Promise<number>;

    getTotalBlocksExecuted(overrides?: CallOverrides): Promise<number>;

    "getTotalBlocksExecuted()"(overrides?: CallOverrides): Promise<number>;

    getTotalBlocksVerified(overrides?: CallOverrides): Promise<number>;

    "getTotalBlocksVerified()"(overrides?: CallOverrides): Promise<number>;

    getTotalPriorityRequests(overrides?: CallOverrides): Promise<BigNumber>;

    "getTotalPriorityRequests()"(overrides?: CallOverrides): Promise<BigNumber>;

    getVerifier(overrides?: CallOverrides): Promise<string>;

    "getVerifier()"(overrides?: CallOverrides): Promise<string>;

    isFunctionFreezable(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isFunctionFreezable(bytes4)"(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isValidator(_address: string, overrides?: CallOverrides): Promise<boolean>;

    "isValidator(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    l2LogsRootHash(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "l2LogsRootHash(uint32)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    l2TransactionBaseCost(
      _gasPrice: BigNumberish,
      _ergsLimit: BigNumberish,
      _calldataLength: BigNumberish,
      _queueType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "l2TransactionBaseCost(uint256,uint256,uint32,uint8)"(
      _gasPrice: BigNumberish,
      _ergsLimit: BigNumberish,
      _calldataLength: BigNumberish,
      _queueType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    movePriorityOpsFromBufferToMainQueue(
      _nOpsToMove: BigNumberish,
      _opTree: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "movePriorityOpsFromBufferToMainQueue(uint256,uint8)"(
      _nOpsToMove: BigNumberish,
      _opTree: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    placeBidForBlocksProcessingAuction(
      _complexityRoot: BigNumberish,
      _opTree: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "placeBidForBlocksProcessingAuction(uint112,uint8)"(
      _complexityRoot: BigNumberish,
      _opTree: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    proposeDiamondCut(
      _facetCuts: {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[],
      _initAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "proposeDiamondCut(tuple[],address)"(
      _facetCuts: {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[],
      _initAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    proveBlocks(
      _committedBlocks: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      _proof: {
        recursiveInput: BigNumberish[];
        proof: BigNumberish[];
        commitments: BigNumberish[];
        vkIndexes: BigNumberish[];
        subproofsLimbs: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "proveBlocks(tuple[],(uint256[],uint256[],uint256[],uint8[],uint256[16]))"(
      _committedBlocks: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      _proof: {
        recursiveInput: BigNumberish[];
        proof: BigNumberish[];
        commitments: BigNumberish[];
        vkIndexes: BigNumberish[];
        subproofsLimbs: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      },
      overrides?: CallOverrides
    ): Promise<void>;

    proveL2LogInclusion(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _log: { sender: string; key: BytesLike; value: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    "proveL2LogInclusion(uint32,uint256,(address,bytes32,bytes32),bytes32[])"(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _log: { sender: string; key: BytesLike; value: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    proveL2MessageInclusion(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _message: { sender: string; data: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    "proveL2MessageInclusion(uint32,uint256,(address,bytes),bytes32[])"(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _message: { sender: string; data: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    requestL2Transaction(
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      _queueType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "requestL2Transaction(address,bytes,uint256,bytes[],uint8)"(
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      _queueType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    revertBlocks(
      _blocksToRevert: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "revertBlocks(uint32)"(
      _blocksToRevert: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    serializeL2Transaction(
      _txId: BigNumberish,
      _layer2Tip: BigNumberish,
      _sender: string,
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      txType: BigNumber;
      from: BigNumber;
      to: BigNumber;
      feeToken: BigNumber;
      ergsLimit: BigNumber;
      ergsPerPubdataByteLimit: BigNumber;
      ergsPrice: BigNumber;
      reserved: [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ];
      data: string;
      signature: string;
      reservedDynamic: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
      7: [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber];
      8: string;
      9: string;
      10: string;
    }>;

    "serializeL2Transaction(uint64,uint256,address,address,bytes,uint256,bytes[])"(
      _txId: BigNumberish,
      _layer2Tip: BigNumberish,
      _sender: string,
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      overrides?: CallOverrides
    ): Promise<{
      txType: BigNumber;
      from: BigNumber;
      to: BigNumber;
      feeToken: BigNumber;
      ergsLimit: BigNumber;
      ergsPerPubdataByteLimit: BigNumber;
      ergsPrice: BigNumber;
      reserved: [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ];
      data: string;
      signature: string;
      reservedDynamic: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: BigNumber;
      6: BigNumber;
      7: [BigNumber, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber];
      8: string;
      9: string;
      10: string;
    }>;

    setValidator(
      _validator: string,
      _active: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setValidator(address,bool)"(
      _validator: string,
      _active: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    unfreezeDiamond(overrides?: CallOverrides): Promise<void>;

    "unfreezeDiamond()"(overrides?: CallOverrides): Promise<void>;

    updatePriorityModeSubEpoch(overrides?: CallOverrides): Promise<void>;

    "updatePriorityModeSubEpoch()"(overrides?: CallOverrides): Promise<void>;

    withdrawAuctionBid(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "withdrawAuctionBid(address)"(
      _recipient: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    BlockCommit(blockNumber: BigNumberish | null): EventFilter;

    BlockExecution(blockNumber: BigNumberish | null): EventFilter;

    BlocksRevert(
      totalBlocksVerified: null,
      totalBlocksCommitted: null
    ): EventFilter;

    DiamondCutProposal(_facetCuts: null, _initAddress: null): EventFilter;

    DiamondCutProposalCancelation(): EventFilter;

    DiamondCutProposalExecution(_diamondCut: null): EventFilter;

    EmergencyDiamondCutApproved(_address: null): EventFilter;

    EmergencyFreeze(): EventFilter;

    MovePriorityOperationsFromBufferToHeap(
      expirationBlock: null,
      operationIDs: null,
      opTree: null
    ): EventFilter;

    NewGovernor(newGovernor: null): EventFilter;

    NewPriorityModeAuctionBid(
      opTree: null,
      sender: null,
      bidAmount: null,
      complexity: null
    ): EventFilter;

    NewPriorityModeSubEpoch(
      subEpoch: null,
      subEpochEndTimestamp: null
    ): EventFilter;

    NewPriorityRequest(
      txId: null,
      txHash: null,
      expirationBlock: null,
      transaction: null,
      factoryDeps: null
    ): EventFilter;

    PriorityModeActivated(): EventFilter;

    Unfreeze(): EventFilter;

    ValidatorStatusUpdate(
      validatorAddress: string | null,
      isActive: null
    ): EventFilter;
  };

  estimateGas: {
    activatePriorityMode(
      _ethExpirationBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "activatePriorityMode(uint32)"(
      _ethExpirationBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    approveEmergencyDiamondCutAsSecurityCouncilMember(
      _diamondCutHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approveEmergencyDiamondCutAsSecurityCouncilMember(bytes32)"(
      _diamondCutHash: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    cancelDiamondCutProposal(overrides?: Overrides): Promise<BigNumber>;

    "cancelDiamondCutProposal()"(overrides?: Overrides): Promise<BigNumber>;

    changeGovernor(
      _newGovernor: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "changeGovernor(address)"(
      _newGovernor: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    commitBlocks(
      _lastCommittedBlockData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      },
      _newBlocksData: {
        newStateRoot: BytesLike;
        blockNumber: BigNumberish;
        feeAccount: string;
        timestamp: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        numberOfLayer2Txs: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        l2Logs: BytesLike;
        l2ArbitraryLengthMessages: BytesLike[];
        deployedContracts: BytesLike;
        storageChanges: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "commitBlocks((uint32,uint16,uint224,bytes32,bytes32,uint256,bytes32,bytes32),tuple[])"(
      _lastCommittedBlockData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      },
      _newBlocksData: {
        newStateRoot: BytesLike;
        blockNumber: BigNumberish;
        feeAccount: string;
        timestamp: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        numberOfLayer2Txs: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        l2Logs: BytesLike;
        l2ArbitraryLengthMessages: BytesLike[];
        deployedContracts: BytesLike;
        storageChanges: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    emergencyFreezeDiamond(overrides?: Overrides): Promise<BigNumber>;

    "emergencyFreezeDiamond()"(overrides?: Overrides): Promise<BigNumber>;

    executeBlocks(
      _blocksData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeBlocks(tuple[])"(
      _blocksData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    executeDiamondCutProposal(
      _diamondCut: {
        facetCuts: {
          facet: string;
          action: BigNumberish;
          isFreezable: boolean;
          selectors: BytesLike[];
        }[];
        initAddress: string;
        initCalldata: BytesLike;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "executeDiamondCutProposal((tuple[],address,bytes))"(
      _diamondCut: {
        facetCuts: {
          facet: string;
          action: BigNumberish;
          isFreezable: boolean;
          selectors: BytesLike[];
        }[];
        initAddress: string;
        initCalldata: BytesLike;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    facetAddress(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "facetAddress(bytes4)"(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    facetAddresses(overrides?: CallOverrides): Promise<BigNumber>;

    "facetAddresses()"(overrides?: CallOverrides): Promise<BigNumber>;

    facetFunctionSelectors(
      _facet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "facetFunctionSelectors(address)"(
      _facet: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    facets(overrides?: CallOverrides): Promise<BigNumber>;

    "facets()"(overrides?: CallOverrides): Promise<BigNumber>;

    facetsExtended(overrides?: CallOverrides): Promise<BigNumber>;

    "facetsExtended()"(overrides?: CallOverrides): Promise<BigNumber>;

    getGovernor(overrides?: CallOverrides): Promise<BigNumber>;

    "getGovernor()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalBlocksCommitted(overrides?: CallOverrides): Promise<BigNumber>;

    "getTotalBlocksCommitted()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalBlocksExecuted(overrides?: CallOverrides): Promise<BigNumber>;

    "getTotalBlocksExecuted()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalBlocksVerified(overrides?: CallOverrides): Promise<BigNumber>;

    "getTotalBlocksVerified()"(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalPriorityRequests(overrides?: CallOverrides): Promise<BigNumber>;

    "getTotalPriorityRequests()"(overrides?: CallOverrides): Promise<BigNumber>;

    getVerifier(overrides?: CallOverrides): Promise<BigNumber>;

    "getVerifier()"(overrides?: CallOverrides): Promise<BigNumber>;

    isFunctionFreezable(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isFunctionFreezable(bytes4)"(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isValidator(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isValidator(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2LogsRootHash(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "l2LogsRootHash(uint32)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    l2TransactionBaseCost(
      _gasPrice: BigNumberish,
      _ergsLimit: BigNumberish,
      _calldataLength: BigNumberish,
      _queueType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "l2TransactionBaseCost(uint256,uint256,uint32,uint8)"(
      _gasPrice: BigNumberish,
      _ergsLimit: BigNumberish,
      _calldataLength: BigNumberish,
      _queueType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    movePriorityOpsFromBufferToMainQueue(
      _nOpsToMove: BigNumberish,
      _opTree: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "movePriorityOpsFromBufferToMainQueue(uint256,uint8)"(
      _nOpsToMove: BigNumberish,
      _opTree: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    placeBidForBlocksProcessingAuction(
      _complexityRoot: BigNumberish,
      _opTree: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "placeBidForBlocksProcessingAuction(uint112,uint8)"(
      _complexityRoot: BigNumberish,
      _opTree: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    proposeDiamondCut(
      _facetCuts: {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[],
      _initAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "proposeDiamondCut(tuple[],address)"(
      _facetCuts: {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[],
      _initAddress: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    proveBlocks(
      _committedBlocks: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      _proof: {
        recursiveInput: BigNumberish[];
        proof: BigNumberish[];
        commitments: BigNumberish[];
        vkIndexes: BigNumberish[];
        subproofsLimbs: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "proveBlocks(tuple[],(uint256[],uint256[],uint256[],uint8[],uint256[16]))"(
      _committedBlocks: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      _proof: {
        recursiveInput: BigNumberish[];
        proof: BigNumberish[];
        commitments: BigNumberish[];
        vkIndexes: BigNumberish[];
        subproofsLimbs: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    proveL2LogInclusion(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _log: { sender: string; key: BytesLike; value: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proveL2LogInclusion(uint32,uint256,(address,bytes32,bytes32),bytes32[])"(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _log: { sender: string; key: BytesLike; value: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    proveL2MessageInclusion(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _message: { sender: string; data: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "proveL2MessageInclusion(uint32,uint256,(address,bytes),bytes32[])"(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _message: { sender: string; data: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    requestL2Transaction(
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      _queueType: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "requestL2Transaction(address,bytes,uint256,bytes[],uint8)"(
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      _queueType: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    revertBlocks(
      _blocksToRevert: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "revertBlocks(uint32)"(
      _blocksToRevert: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    serializeL2Transaction(
      _txId: BigNumberish,
      _layer2Tip: BigNumberish,
      _sender: string,
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "serializeL2Transaction(uint64,uint256,address,address,bytes,uint256,bytes[])"(
      _txId: BigNumberish,
      _layer2Tip: BigNumberish,
      _sender: string,
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setValidator(
      _validator: string,
      _active: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setValidator(address,bool)"(
      _validator: string,
      _active: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    unfreezeDiamond(overrides?: Overrides): Promise<BigNumber>;

    "unfreezeDiamond()"(overrides?: Overrides): Promise<BigNumber>;

    updatePriorityModeSubEpoch(overrides?: Overrides): Promise<BigNumber>;

    "updatePriorityModeSubEpoch()"(overrides?: Overrides): Promise<BigNumber>;

    withdrawAuctionBid(
      _recipient: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "withdrawAuctionBid(address)"(
      _recipient: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    activatePriorityMode(
      _ethExpirationBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "activatePriorityMode(uint32)"(
      _ethExpirationBlock: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    approveEmergencyDiamondCutAsSecurityCouncilMember(
      _diamondCutHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approveEmergencyDiamondCutAsSecurityCouncilMember(bytes32)"(
      _diamondCutHash: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    cancelDiamondCutProposal(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "cancelDiamondCutProposal()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    changeGovernor(
      _newGovernor: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "changeGovernor(address)"(
      _newGovernor: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    commitBlocks(
      _lastCommittedBlockData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      },
      _newBlocksData: {
        newStateRoot: BytesLike;
        blockNumber: BigNumberish;
        feeAccount: string;
        timestamp: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        numberOfLayer2Txs: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        l2Logs: BytesLike;
        l2ArbitraryLengthMessages: BytesLike[];
        deployedContracts: BytesLike;
        storageChanges: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "commitBlocks((uint32,uint16,uint224,bytes32,bytes32,uint256,bytes32,bytes32),tuple[])"(
      _lastCommittedBlockData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      },
      _newBlocksData: {
        newStateRoot: BytesLike;
        blockNumber: BigNumberish;
        feeAccount: string;
        timestamp: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        numberOfLayer2Txs: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        l2Logs: BytesLike;
        l2ArbitraryLengthMessages: BytesLike[];
        deployedContracts: BytesLike;
        storageChanges: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    emergencyFreezeDiamond(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "emergencyFreezeDiamond()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    executeBlocks(
      _blocksData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeBlocks(tuple[])"(
      _blocksData: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    executeDiamondCutProposal(
      _diamondCut: {
        facetCuts: {
          facet: string;
          action: BigNumberish;
          isFreezable: boolean;
          selectors: BytesLike[];
        }[];
        initAddress: string;
        initCalldata: BytesLike;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "executeDiamondCutProposal((tuple[],address,bytes))"(
      _diamondCut: {
        facetCuts: {
          facet: string;
          action: BigNumberish;
          isFreezable: boolean;
          selectors: BytesLike[];
        }[];
        initAddress: string;
        initCalldata: BytesLike;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    facetAddress(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "facetAddress(bytes4)"(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    facetAddresses(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "facetAddresses()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    facetFunctionSelectors(
      _facet: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "facetFunctionSelectors(address)"(
      _facet: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    facets(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "facets()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    facetsExtended(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "facetsExtended()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGovernor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getGovernor()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalBlocksCommitted(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTotalBlocksCommitted()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalBlocksExecuted(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTotalBlocksExecuted()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalBlocksVerified(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTotalBlocksVerified()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTotalPriorityRequests(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTotalPriorityRequests()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getVerifier(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getVerifier()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isFunctionFreezable(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isFunctionFreezable(bytes4)"(
      _selector: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isValidator(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isValidator(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2LogsRootHash(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "l2LogsRootHash(uint32)"(
      blockNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    l2TransactionBaseCost(
      _gasPrice: BigNumberish,
      _ergsLimit: BigNumberish,
      _calldataLength: BigNumberish,
      _queueType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "l2TransactionBaseCost(uint256,uint256,uint32,uint8)"(
      _gasPrice: BigNumberish,
      _ergsLimit: BigNumberish,
      _calldataLength: BigNumberish,
      _queueType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    movePriorityOpsFromBufferToMainQueue(
      _nOpsToMove: BigNumberish,
      _opTree: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "movePriorityOpsFromBufferToMainQueue(uint256,uint8)"(
      _nOpsToMove: BigNumberish,
      _opTree: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    placeBidForBlocksProcessingAuction(
      _complexityRoot: BigNumberish,
      _opTree: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "placeBidForBlocksProcessingAuction(uint112,uint8)"(
      _complexityRoot: BigNumberish,
      _opTree: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    proposeDiamondCut(
      _facetCuts: {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[],
      _initAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "proposeDiamondCut(tuple[],address)"(
      _facetCuts: {
        facet: string;
        action: BigNumberish;
        isFreezable: boolean;
        selectors: BytesLike[];
      }[],
      _initAddress: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    proveBlocks(
      _committedBlocks: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      _proof: {
        recursiveInput: BigNumberish[];
        proof: BigNumberish[];
        commitments: BigNumberish[];
        vkIndexes: BigNumberish[];
        subproofsLimbs: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "proveBlocks(tuple[],(uint256[],uint256[],uint256[],uint8[],uint256[16]))"(
      _committedBlocks: {
        blockNumber: BigNumberish;
        numberOfLayer1Txs: BigNumberish;
        priorityOperationsComplexity: BigNumberish;
        priorityOperationsHash: BytesLike;
        l2LogsTreeRoot: BytesLike;
        timestamp: BigNumberish;
        stateRoot: BytesLike;
        commitment: BytesLike;
      }[],
      _proof: {
        recursiveInput: BigNumberish[];
        proof: BigNumberish[];
        commitments: BigNumberish[];
        vkIndexes: BigNumberish[];
        subproofsLimbs: [
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish,
          BigNumberish
        ];
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    proveL2LogInclusion(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _log: { sender: string; key: BytesLike; value: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proveL2LogInclusion(uint32,uint256,(address,bytes32,bytes32),bytes32[])"(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _log: { sender: string; key: BytesLike; value: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proveL2MessageInclusion(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _message: { sender: string; data: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "proveL2MessageInclusion(uint32,uint256,(address,bytes),bytes32[])"(
      _blockNumber: BigNumberish,
      _index: BigNumberish,
      _message: { sender: string; data: BytesLike },
      _proof: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    requestL2Transaction(
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      _queueType: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "requestL2Transaction(address,bytes,uint256,bytes[],uint8)"(
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      _queueType: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    revertBlocks(
      _blocksToRevert: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revertBlocks(uint32)"(
      _blocksToRevert: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    serializeL2Transaction(
      _txId: BigNumberish,
      _layer2Tip: BigNumberish,
      _sender: string,
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "serializeL2Transaction(uint64,uint256,address,address,bytes,uint256,bytes[])"(
      _txId: BigNumberish,
      _layer2Tip: BigNumberish,
      _sender: string,
      _contractAddressL2: string,
      _calldata: BytesLike,
      _ergsLimit: BigNumberish,
      _factoryDeps: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setValidator(
      _validator: string,
      _active: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setValidator(address,bool)"(
      _validator: string,
      _active: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    unfreezeDiamond(overrides?: Overrides): Promise<PopulatedTransaction>;

    "unfreezeDiamond()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    updatePriorityModeSubEpoch(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updatePriorityModeSubEpoch()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    withdrawAuctionBid(
      _recipient: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "withdrawAuctionBid(address)"(
      _recipient: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
