/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ITridentCallee,
  ITridentCalleeInterface,
} from "../ITridentCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "tridentMintCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "tridentSwapCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITridentCallee__factory {
  static readonly abi = _abi;
  static createInterface(): ITridentCalleeInterface {
    return new utils.Interface(_abi) as ITridentCalleeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITridentCallee {
    return new Contract(address, _abi, signerOrProvider) as ITridentCallee;
  }
}
