// Generated by CoffeeScript 2.5.1
// # Cloudfare extra status codes

// Cloudflare's reverse proxy service expands the 5xx error class to signal issues with the origin server.
var k, ref, status, v;

status = require('.');

// Import default status codes.
for (k in status) {
  v = status[k];
  if (k === 'extra') {
    continue;
  }
  module.exports[k] = v;
}

ref = status.extra.cloudflare;
// Merge default status codes with Cloudflare status codes.
for (k in ref) {
  v = ref[k];
  module.exports[k] = v;
}
