/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IMigrator } from "../IMigrator";

export class IMigrator__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMigrator {
    return new Contract(address, _abi, signerOrProvider) as IMigrator;
  }
}

const _abi = [
  {
    inputs: [],
    name: "desiredLiquidity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
