import { ChainId } from '../../../chain/index.js'
import { BentoBoxChainId } from '../../bentobox.js'
import {
  DECENTRALIZED_NETWORK_HOST,
  SUSHI_DEDICATED_GOLDSKY_HOST,
} from '../hosts.js'

export const BENTOBOX_SUBGRAPH_URL: Partial<Record<BentoBoxChainId, string>> = {
  [ChainId.ETHEREUM]: `${DECENTRALIZED_NETWORK_HOST}/8HYeoDopVqqvb5RJEV2TtSzFsouYPz8cownnG3mbhiGy`,
  [ChainId.POLYGON]: `${DECENTRALIZED_NETWORK_HOST}/6kJg5kFoQY8B8Ge2hqswHMqZDcmsR1TLUUz7AKov69fy`,
  [ChainId.AVALANCHE]: `${DECENTRALIZED_NETWORK_HOST}/EhYaJodF1WQjKgxx1ZC63goeCwp5swD4AQRdaKXBm2xk`,
  [ChainId.BSC]: `${DECENTRALIZED_NETWORK_HOST}/BggyE3r5snDsjx19jgZcbiBH7cbtrkpjvyGLFHMdXekd`,
  [ChainId.FANTOM]: `${DECENTRALIZED_NETWORK_HOST}/AWD9Ca7KNZg7grfWosKTRqZTjPrJVgS5P5b37pDpN4CT`,
  [ChainId.GNOSIS]: `${DECENTRALIZED_NETWORK_HOST}/9jn9kA6SKCNxXQSqb93zZPLdLaru4FeZBwLNWAK4nfZ2`,
  [ChainId.ARBITRUM]: `${DECENTRALIZED_NETWORK_HOST}/JZFyMKR4jnsFQ58q7dT6nbXenTzNgE176zTejc6Gf8Z`,
  [ChainId.CELO]: `${DECENTRALIZED_NETWORK_HOST}/5DwkvjxPGVFFaWEMM68g1yztDdhCgJEYAxS6FuhkajzR`,
  [ChainId.MOONRIVER]: `${DECENTRALIZED_NETWORK_HOST}/73XEV6UQKpPSJn68WZBAYTwALcZtFJkFYn58ZoZUb7tn`,
  [ChainId.MOONBEAM]: `${DECENTRALIZED_NETWORK_HOST}/7wA5gqWNP4E1dPWBsTYvz5eQSDbtYDFgyU5BGdHr2UKp`,
  [ChainId.OPTIMISM]: `${DECENTRALIZED_NETWORK_HOST}/8b4Hy4Kn7jCNAf9JFrqHb24LsqmapG4HrAsCrwdJf9Nu`,
  [ChainId.HARMONY]: `${DECENTRALIZED_NETWORK_HOST}/Bioj7N3Rf2n7iBq9PVoaMie3WiuzPze9NMi7aSye7LFc`,
  [ChainId.BTTC]: `${SUSHI_DEDICATED_GOLDSKY_HOST}/sushiswap/bentobox-bttc/gn`,
}
