/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPolyFaucet } from "../IPolyFaucet";

export class IPolyFaucet__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPolyFaucet {
    return new Contract(address, _abi, signerOrProvider) as IPolyFaucet;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "getTokens",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
