/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface SushiMakerExploitMockInterface extends ethers.utils.Interface {
  functions: {
    "convert(address,address)": FunctionFragment;
    "sushiMaker()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "convert",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "sushiMaker",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "convert", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sushiMaker", data: BytesLike): Result;

  events: {};
}

export class SushiMakerExploitMock extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: SushiMakerExploitMockInterface;

  functions: {
    convert(
      token0: string,
      token1: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "convert(address,address)"(
      token0: string,
      token1: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    sushiMaker(overrides?: CallOverrides): Promise<[string]>;

    "sushiMaker()"(overrides?: CallOverrides): Promise<[string]>;
  };

  convert(
    token0: string,
    token1: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "convert(address,address)"(
    token0: string,
    token1: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  sushiMaker(overrides?: CallOverrides): Promise<string>;

  "sushiMaker()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    convert(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "convert(address,address)"(
      token0: string,
      token1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sushiMaker(overrides?: CallOverrides): Promise<string>;

    "sushiMaker()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    convert(
      token0: string,
      token1: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "convert(address,address)"(
      token0: string,
      token1: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    sushiMaker(overrides?: CallOverrides): Promise<BigNumber>;

    "sushiMaker()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    convert(
      token0: string,
      token1: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "convert(address,address)"(
      token0: string,
      token1: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    sushiMaker(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "sushiMaker()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
