name: 🐛 Bug report
description: Create a report to help us squash bugs!
title: "[Bug]: "
labels: ["T:Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Before smashing the submit button please review the template.
        Please also ensure that this is not a duplicate issue :)

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: If applicable, specify the version or branch you're using
      placeholder: main, etc.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce?
      description: If applicable could you describe how we could reproduce the bug
      placeholder: Tell us how to reproduce the bug!
    validations:
      required: false
