import { AddressMap } from '../types';
export declare const SUSHI_ADDRESS: AddressMap;
export declare const USDC_ADDRESS: AddressMap;
export declare const USD_ADDRESS: AddressMap;
export declare const WETH9_ADDRESS: AddressMap;
export declare const WNATIVE_ADDRESS: AddressMap;
export declare const DAI_ADDRESS: AddressMap;
export declare const USDT_ADDRESS: AddressMap;
export declare const MIM_ADDRESS: AddressMap;
export declare const FRAX_ADDRESS: AddressMap;
export declare const FACTORY_ADDRESS: AddressMap;
export declare const ROUTER_ADDRESS: AddressMap;
export declare const MASTERCHEF_ADDRESS: AddressMap;
export declare const BAR_ADDRESS: AddressMap;
export declare const MAKER_ADDRESS: AddressMap;
export declare const TIMELOCK_ADDRESS: AddressMap;
export declare const BENTOBOX_ADDRESS: AddressMap;
export declare const KASHI_ADDRESS: AddressMap;
export declare const SUSHISWAP_SWAPPER_ADDRESS: AddressMap;
export declare const SUSHISWAP_MULTISWAPPER_ADDRESS: AddressMap;
export declare const SUSHISWAP_MULTI_EXACT_SWAPPER_ADDRESS: AddressMap;
export declare const PEGGED_ORACLE_ADDRESS = "0x6cbfbB38498Df0E1e7A4506593cDB02db9001564";
export declare const SUSHISWAP_TWAP_0_ORACLE_ADDRESS = "0x66F03B0d30838A3fee971928627ea6F59B236065";
export declare const SUSHISWAP_TWAP_1_ORACLE_ADDRESS = "0x0D51b575591F8f74a2763Ade75D3CDCf6789266f";
export declare const CHAINLINK_ORACLE_ADDRESS: AddressMap;
export declare const BORING_HELPER_ADDRESS: AddressMap;
export declare const MINICHEF_ADDRESS: AddressMap;
export declare const MASTERCHEF_V2_ADDRESS: AddressMap;
export declare const ENS_REGISTRAR_ADDRESS: AddressMap;
export declare const ZAPPER_ADDRESS: AddressMap;
export declare const MERKLE_DISTRIBUTOR_ADDRESS: AddressMap;
export declare const MULTICALL2_ADDRESS: AddressMap;
export declare const BALANCE_FETCHER_ADDRESS: AddressMap;
export declare const MULTISIG_ADDRESS: AddressMap;
