# sources:
#   - name: BentoBox
#     handler:
#       graphql:
#         endpoint: https://{context.host:api.thegraph.com}/subgraphs/name/{context.name:matthewlilley/bentobox-ethereum}
#     transforms:
#       - addSourceName: true
#       - prefix:
#           value: bentobox_
#           includeRootOperations: true
#           includeTypes: false
#       - autoPagination:
#           validateSchema: true

sources:
  - name: BentoBox
    handler:
      graphql:
        # Default value is bentobox-polygon
        # This is needed for the initial introspection on buildtime
        endpoint: https://{context.host:api.thegraph.com/subgraphs/name}/{context.name:sushiswap/bentobox-polygon}
  - name: TheGraph
    handler:
      graphql:
        endpoint: https://{context.node:api.thegraph.com/index-node/graphql}

additionalTypeDefs: |
  extend type BentoBoxKpi {
    chainId: BigInt
  }
  extend type StrategyKpi {
    chainId: BigInt
  }
  extend type Query {
    crossChainBentoBoxKpis(
      first: Int!
      chainIds: [BigInt!]!
    ): [BentoBoxKpi!]!
    crossChainStrategyKpis(
      skip: Int = 0
      first: Int = 100
      where: StrategyKpi_filter
      orderBy: StrategyKpi_orderBy
      orderDirection: OrderDirection
      block: Block_height
      chainIds: [Int!]!
    ): [StrategyKpi!]!
  }

  enum SubgraphType {
    Current
    Pending
  }
  enum SubgraphStatus {
    Synced
    Syncing
    Failed
  }
  type Subgraph {
    subgraphName: String
    subgraphId: String
    type: SubgraphType
    status: SubgraphStatus
    startBlock: BigInt
    lastSyncedBlock: BigInt
    chainHeadBlock: BigInt
    hasFailed: Boolean
    nonFatalErrorCount: BigInt
    entityCount: BigInt
  }
  input SubgraphWithNode {
    subgraphName: String!
    nodeUrl: String!
  }
  extend type Query {
    subgraphs(subgraphs: [SubgraphWithNode!]!, type: SubgraphType!): [Subgraph!]!
  }

additionalResolvers:
  - ./resolvers.ts

documents:
  - ./query.graphql

codegen:
  contextType: 'MeshContext & { chainId: string; name: string; host: string }'
