sources:
  - name: Trident
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:sushi-qa/trident-optimism}
        retry: 3
    # transforms:
    #   - autoPagination:
    #       validateSchema: true

  - name: V2
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:sameepsi/quickswap06}
        retry: 3
    transforms:
      - prefix:
          value: V2_
          includeRootOperations: true
          includeTypes: true
      # - autoPagination:
      #     validateSchema: true   
  - name: V3
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:uniswap/uniswap-v3}
        retry: 3
    transforms:
      - prefix:
          value: V3_
          includeRootOperations: true
          includeTypes: true
          
  # - name: PancakeSwap
  #   handler:
  #     graphql:
  #       endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:pancakeswap/pairs}
  #       retry: 3
  #   transforms:
  #     - prefix:
  #         value: MINIMAL_
  #         includeRootOperations: true
  #         includeTypes: true
  - name: TraderJoe
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:traderjoe-xyz/exchange}
        retry: 3
    transforms:
      - prefix:
          value: TJ_
          includeRootOperations: true
          includeTypes: true
  - name: Messari
    handler:
      graphql:
        endpoint: https://{context.host:api.thegraph.com}/{context.path:subgraphs/name}/{context.name:messari/apeswap-polygon}
        retry: 3
    transforms:
      - prefix:
          value: MESSARI_
          includeRootOperations: true
          includeTypes: true
documents:
  - ./query.graphql

codegen:
  contextType: 'MeshContext & { name: string; host: string; path: string; }'

