/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPositionManager,
  IPositionManagerInterface,
} from "../IPositionManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token0",
        type: "address",
      },
      {
        internalType: "address",
        name: "token1",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "native",
        type: "bool",
      },
    ],
    name: "mintCallback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPositionManager__factory {
  static readonly abi = _abi;
  static createInterface(): IPositionManagerInterface {
    return new utils.Interface(_abi) as IPositionManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPositionManager {
    return new Contract(address, _abi, signerOrProvider) as IPositionManager;
  }
}
