import { ChainId } from '@sushiswap/chain'
import {
  STARGATE_BUSD,
  STARGATE_BUSD_ADDRESS,
  STARGATE_DAI,
  STARGATE_DAI_ADDRESS,
  STARGATE_ETH,
  STARGATE_ETH_ADDRESS,
  STARGATE_FRAX,
  STARGATE_FRAX_ADDRESS,
  STARGATE_MAI,
  STARGATE_MAI_ADDRESS,
  STARGATE_USDC,
  STARGATE_USDC_ADDRESS,
  STARGATE_USDT,
  STARGATE_USDT_ADDRESS,
  StargateChainId,
} from '.'
import { Token } from '@sushiswap/currency'

type Address = `0x${string}`

// https://stargateprotocol.gitbook.io/stargate/developers/stargate-chain-paths

const ETHEREUM_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[ChainId.ETHEREUM]]: [
    STARGATE_BUSD[ChainId.BSC],
    STARGATE_USDT[ChainId.BSC],
    STARGATE_USDC[ChainId.AVALANCHE],
    STARGATE_USDT[ChainId.AVALANCHE],
    STARGATE_USDC[ChainId.POLYGON],
    STARGATE_USDT[ChainId.POLYGON],
    STARGATE_USDC[ChainId.ARBITRUM],
    STARGATE_USDT[ChainId.ARBITRUM],
    STARGATE_USDC[ChainId.OPTIMISM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_USDT_ADDRESS[ChainId.ETHEREUM]]: [
    STARGATE_USDT[ChainId.BSC],
    STARGATE_USDC[ChainId.AVALANCHE],
    STARGATE_USDT[ChainId.AVALANCHE],
    STARGATE_USDC[ChainId.POLYGON],
    STARGATE_USDT[ChainId.POLYGON],
    STARGATE_USDC[ChainId.ARBITRUM],
    STARGATE_USDT[ChainId.ARBITRUM],
    STARGATE_USDC[ChainId.OPTIMISM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_DAI_ADDRESS[ChainId.ETHEREUM]]: [STARGATE_DAI[ChainId.POLYGON], STARGATE_DAI[ChainId.OPTIMISM]],
  [STARGATE_FRAX_ADDRESS[ChainId.ETHEREUM]]: [
    STARGATE_FRAX[ChainId.AVALANCHE],
    STARGATE_FRAX[ChainId.ARBITRUM],
    STARGATE_FRAX[ChainId.OPTIMISM],
  ],
  [STARGATE_ETH_ADDRESS[ChainId.ETHEREUM]]: [STARGATE_ETH[ChainId.ARBITRUM], STARGATE_ETH[ChainId.OPTIMISM]],
  [STARGATE_MAI_ADDRESS[ChainId.ETHEREUM]]: [
    STARGATE_MAI[ChainId.BSC],
    STARGATE_MAI[ChainId.AVALANCHE],
    STARGATE_MAI[ChainId.POLYGON],
    STARGATE_MAI[ChainId.ARBITRUM],
    STARGATE_MAI[ChainId.OPTIMISM],
  ],
}

const BSC_CHAIN_PATHS = {
  [STARGATE_BUSD_ADDRESS[ChainId.BSC]]: [
    STARGATE_USDC[ChainId.ETHEREUM],
    STARGATE_USDT[ChainId.ETHEREUM],
    STARGATE_USDC[ChainId.AVALANCHE],
    STARGATE_USDT[ChainId.AVALANCHE],
    STARGATE_USDC[ChainId.POLYGON],
    STARGATE_USDT[ChainId.POLYGON],
    STARGATE_USDC[ChainId.ARBITRUM],
    STARGATE_USDT[ChainId.ARBITRUM],
    STARGATE_USDC[ChainId.OPTIMISM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_USDT_ADDRESS[ChainId.BSC]]: [
    STARGATE_USDC[ChainId.ETHEREUM],
    STARGATE_USDT[ChainId.ETHEREUM],
    STARGATE_USDC[ChainId.AVALANCHE],
    STARGATE_USDT[ChainId.AVALANCHE],
    STARGATE_USDC[ChainId.POLYGON],
    STARGATE_USDT[ChainId.POLYGON],
    STARGATE_USDC[ChainId.ARBITRUM],
    STARGATE_USDT[ChainId.ARBITRUM],
    STARGATE_USDC[ChainId.OPTIMISM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_MAI_ADDRESS[ChainId.BSC]]: [
    STARGATE_MAI[ChainId.ETHEREUM],
    STARGATE_MAI[ChainId.AVALANCHE],
    STARGATE_MAI[ChainId.POLYGON],
    STARGATE_MAI[ChainId.ARBITRUM],
    STARGATE_MAI[ChainId.OPTIMISM],
  ],
}

const AVALANCE_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[ChainId.AVALANCHE]]: [
    STARGATE_USDC[ChainId.ETHEREUM],
    STARGATE_USDT[ChainId.ETHEREUM],
    STARGATE_BUSD[ChainId.BSC],
    STARGATE_USDT[ChainId.BSC],
    STARGATE_USDC[ChainId.POLYGON],
    STARGATE_USDT[ChainId.POLYGON],
    STARGATE_USDC[ChainId.ARBITRUM],
    STARGATE_USDT[ChainId.ARBITRUM],
    STARGATE_USDC[ChainId.OPTIMISM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_USDT_ADDRESS[ChainId.AVALANCHE]]: [
    STARGATE_USDC[ChainId.ETHEREUM],
    STARGATE_USDT[ChainId.ETHEREUM],
    STARGATE_BUSD[ChainId.BSC],
    STARGATE_USDT[ChainId.BSC],
    STARGATE_USDC[ChainId.POLYGON],
    STARGATE_USDT[ChainId.POLYGON],
    STARGATE_USDC[ChainId.ARBITRUM],
    STARGATE_USDT[ChainId.ARBITRUM],
    STARGATE_USDC[ChainId.OPTIMISM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_FRAX_ADDRESS[ChainId.AVALANCHE]]: [
    STARGATE_FRAX[ChainId.ETHEREUM],
    STARGATE_FRAX[ChainId.ARBITRUM],
    STARGATE_FRAX[ChainId.OPTIMISM],
  ],
  [STARGATE_MAI_ADDRESS[ChainId.AVALANCHE]]: [
    STARGATE_MAI[ChainId.ETHEREUM],
    STARGATE_MAI[ChainId.BSC],
    STARGATE_MAI[ChainId.POLYGON],
    STARGATE_MAI[ChainId.ARBITRUM],
    STARGATE_MAI[ChainId.OPTIMISM],
  ],
}

const POLYGON_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[ChainId.POLYGON]]: [
    STARGATE_USDC[ChainId.ETHEREUM],
    STARGATE_USDT[ChainId.ETHEREUM],
    STARGATE_BUSD[ChainId.BSC],
    STARGATE_USDT[ChainId.BSC],
    STARGATE_USDC[ChainId.AVALANCHE],
    STARGATE_USDT[ChainId.AVALANCHE],
    STARGATE_USDC[ChainId.ARBITRUM],
    STARGATE_USDT[ChainId.ARBITRUM],
    STARGATE_USDC[ChainId.OPTIMISM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_USDT_ADDRESS[ChainId.POLYGON]]: [
    STARGATE_USDC[ChainId.ETHEREUM],
    STARGATE_USDT[ChainId.ETHEREUM],
    STARGATE_BUSD[ChainId.BSC],
    STARGATE_USDT[ChainId.BSC],
    STARGATE_USDC[ChainId.AVALANCHE],
    STARGATE_USDT[ChainId.AVALANCHE],
    STARGATE_USDC[ChainId.ARBITRUM],
    STARGATE_USDT[ChainId.ARBITRUM],
    STARGATE_USDC[ChainId.OPTIMISM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_DAI_ADDRESS[ChainId.POLYGON]]: [STARGATE_DAI[ChainId.ETHEREUM], STARGATE_DAI[ChainId.OPTIMISM]],
  [STARGATE_MAI_ADDRESS[ChainId.POLYGON]]: [
    STARGATE_MAI[ChainId.ETHEREUM],
    STARGATE_MAI[ChainId.BSC],
    STARGATE_MAI[ChainId.AVALANCHE],
    STARGATE_MAI[ChainId.ARBITRUM],
    STARGATE_MAI[ChainId.OPTIMISM],
  ],
}

const ARBITRUM_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[ChainId.ARBITRUM]]: [
    STARGATE_USDC[ChainId.ETHEREUM],
    STARGATE_USDT[ChainId.ETHEREUM],
    STARGATE_BUSD[ChainId.BSC],
    STARGATE_USDT[ChainId.BSC],
    STARGATE_USDC[ChainId.AVALANCHE],
    STARGATE_USDT[ChainId.AVALANCHE],
    STARGATE_USDC[ChainId.POLYGON],
    STARGATE_USDT[ChainId.POLYGON],
    STARGATE_USDC[ChainId.OPTIMISM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_USDT_ADDRESS[ChainId.ARBITRUM]]: [
    STARGATE_USDC[ChainId.ETHEREUM],
    STARGATE_USDT[ChainId.ETHEREUM],
    STARGATE_BUSD[ChainId.BSC],
    STARGATE_USDT[ChainId.BSC],
    STARGATE_USDC[ChainId.AVALANCHE],
    STARGATE_USDT[ChainId.AVALANCHE],
    STARGATE_USDC[ChainId.POLYGON],
    STARGATE_USDT[ChainId.POLYGON],
    STARGATE_USDC[ChainId.OPTIMISM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_FRAX_ADDRESS[ChainId.ARBITRUM]]: [
    STARGATE_FRAX[ChainId.ETHEREUM],
    STARGATE_FRAX[ChainId.AVALANCHE],
    STARGATE_FRAX[ChainId.OPTIMISM],
  ],
  [STARGATE_ETH_ADDRESS[ChainId.ARBITRUM]]: [STARGATE_ETH[ChainId.ETHEREUM], STARGATE_ETH[ChainId.OPTIMISM]],
  [STARGATE_MAI_ADDRESS[ChainId.ARBITRUM]]: [
    STARGATE_MAI[ChainId.ETHEREUM],
    STARGATE_MAI[ChainId.BSC],
    STARGATE_MAI[ChainId.AVALANCHE],
    STARGATE_MAI[ChainId.POLYGON],
    STARGATE_MAI[ChainId.OPTIMISM],
  ],
}

const OPTIMISM_CHAIN_PATHS = {
  [STARGATE_USDC_ADDRESS[ChainId.OPTIMISM]]: [
    STARGATE_USDC[ChainId.ETHEREUM],
    STARGATE_USDT[ChainId.ETHEREUM],
    STARGATE_BUSD[ChainId.BSC],
    STARGATE_USDT[ChainId.BSC],
    STARGATE_USDC[ChainId.AVALANCHE],
    STARGATE_USDT[ChainId.AVALANCHE],
    STARGATE_USDC[ChainId.POLYGON],
    STARGATE_USDT[ChainId.POLYGON],
    STARGATE_USDC[ChainId.ARBITRUM],
    STARGATE_USDT[ChainId.ARBITRUM],
    STARGATE_USDC[ChainId.FANTOM],
  ],
  [STARGATE_DAI_ADDRESS[ChainId.OPTIMISM]]: [STARGATE_DAI[ChainId.ETHEREUM], STARGATE_DAI[ChainId.POLYGON]],
  [STARGATE_FRAX_ADDRESS[ChainId.OPTIMISM]]: [
    STARGATE_FRAX[ChainId.ETHEREUM],
    STARGATE_FRAX[ChainId.AVALANCHE],
    STARGATE_FRAX[ChainId.ARBITRUM],
  ],
  [STARGATE_ETH_ADDRESS[ChainId.OPTIMISM]]: [STARGATE_ETH[ChainId.ETHEREUM], STARGATE_ETH[ChainId.ARBITRUM]],
  [STARGATE_MAI_ADDRESS[ChainId.OPTIMISM]]: [
    STARGATE_MAI[ChainId.ETHEREUM],
    STARGATE_MAI[ChainId.BSC],
    STARGATE_MAI[ChainId.AVALANCHE],
    STARGATE_MAI[ChainId.POLYGON],
    STARGATE_MAI[ChainId.ARBITRUM],
  ],
}

export const STARGATE_CHAIN_PATHS: Record<StargateChainId, Record<Address, Token[]>> = {
  [ChainId.ETHEREUM]: ETHEREUM_CHAIN_PATHS,
  [ChainId.BSC]: BSC_CHAIN_PATHS,
  [ChainId.AVALANCHE]: AVALANCE_CHAIN_PATHS,
  [ChainId.POLYGON]: POLYGON_CHAIN_PATHS,
  [ChainId.ARBITRUM]: ARBITRUM_CHAIN_PATHS,
  [ChainId.OPTIMISM]: OPTIMISM_CHAIN_PATHS,
}
