name: "Install"
description: "Install dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up foundry
      uses: foundry-rs/foundry-toolchain@v1

    # - name: Install playwright
    #   shell: bash
    #   run: npx playwright install --with-deps chromium

    - name: Set up pnpm
      uses: sushi-labs/actions/.github/actions/pnpm@master