import type { Token } from '~stellar/_common/lib/types/token.type'

// These are TESTNET tokens (curated by StellarExpert)
// See: https://api.stellar.expert/explorer/testnet/asset-list/top50
// See https://testnet.stellarchain.io/assets
export const baseTokens: Token[] = [
  {
    code: 'XLM',
    issuer: '',
    contract: 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC',
    name: 'XLM',
    org: 'stellar',
    domain: 'stellar.org',
    decimals: 7,
  },
  {
    code: 'HYPE',
    issuer: '',
    contract: 'CCKYIGXKXH7PBIUQ4D54OIB3ZB4QKCJEAG3M7PW3KDKT5RTGMXNK2PUT',
    name: 'HYPE',
    org: 'hypotenuselabs',
    decimals: 7,
  },
  {
    code: 'HYPED',
    issuer: '',
    contract: 'CCKYI4LNVVIUCEUAKDKNEJKOSVLLTOVJZJRGNZH5D4PINLKUB2O5UZGP',
    name: 'HYPE',
    org: 'hypotenuselabs',
    decimals: 7,
  },
  {
    code: 'HYPEE',
    issuer: '',
    contract: 'CBUUT73R2K27PDNAAH3IUN5GCEJAS7ZREOUXPEDS7K4M4QXDWJSAFZXX',
    name: 'HYPE',
    org: 'hypotenuselabs',
    decimals: 7,
  },
  {
    code: 'SUSHI',
    issuer: '',
    contract: 'CAGOAU6G6JHAWABEGGUXQXOC4FMFZSY4SDKCVW47FS4ULYHEI5TSGJAT',
    name: 'SUSHI',
    org: 'sushiswap',
    decimals: 7,
  },
  {
    code: 'STELLA',
    issuer: '',
    contract: 'CA75JDQYO5RQC6H5USNYV3J26MGS476XTYSUDMEONHLEZCKOBSTEWZ5W',
    name: 'STELLA',
    org: 'hypotenuselabs',
    decimals: 7,
  },
  {
    code: 'HYPEd',
    issuer: '',
    contract: 'CAOYWTNZT5VBDPCNHSHS4SPQIYOZNJW6BUJL3KR6R2X4TVOYU46HOUYU',
    name: 'HYPEd',
    org: 'hypotenuselabs',
    decimals: 7,
  },
  {
    code: 'HYPEe',
    issuer: '',
    contract: 'CA2BMGVWFVJKRGJ5LEC6YT5GK4UGMGF2QZXLAYRVMF6BUOF34JTKLAPI',
    name: 'HYPEe',
    org: 'hypotenuselabs',
    decimals: 7,
  },
  {
    code: 'USDC',
    contract: 'CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA',
    issuer: 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5',
    name: 'USDC',
    org: 'centre',
    domain: 'centre.io',
    decimals: 7,
    isStable: true,
  },
  {
    code: 'SSLX',
    issuer: '',
    contract: 'CBHBD77PWZ3AXPQVYVDBHDKEMVNOR26UZUZHWCB6QC7J5SETQPRUQAS4',
    name: 'SSLX',
    org: 'stellar',
    decimals: 7,
  },
  {
    code: 'BTCLN',
    issuer: '',
    contract: 'CBHIQPUXLFLC5O44ZJVUTCL5LMZFLVGU5DEIGSYKBSAPFMOGTKOQEPFM',
    name: 'BTCLN',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'HYPEc',
    issuer: '',
    contract: 'CCSG4CCSKDAZ2UWZZNFK2FLJJQ3T443SUIAPAJR436WNOSFXPYOT47C2',
    name: 'HypeC',
    org: 'hypotenuselabs',
    decimals: 7,
  },
  // OLD: remove if needed
  {
    code: 'HYPEa',
    issuer: '',
    contract: 'CCUYO46LKVYRQL63LIIMGWVURVBQVETKO26G5OK5XVB5S4GKMGPKXNYJ',
    name: 'HYPEa',
    org: 'hypotenuselabs',
    decimals: 7,
  },
  {
    code: 'HYPEb',
    issuer: '',
    contract: 'CBQMJZL4U4MAQNHKNZZ2CAAKOJEDKL4J4C6AVFQL4CSKNLZU6H3PD5O7',
    name: 'HYPEb',
    org: 'hypotenuselabs',
    decimals: 7,
  },
]
