import type { Token } from '~stellar/_common/lib/types/token.type'

// These are TESTNET tokens (curated by StellarExpert)
// See: https://api.stellar.expert/explorer/testnet/asset-list/top50
export const baseTokens: Token[] = [
  {
    code: 'XLM',
    issuer: '',
    contract: 'CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC',
    name: 'XLM',
    org: 'stellar',
    domain: 'stellar.org',
    decimals: 7,
  },
  {
    code: 'USDC',
    issuer: 'GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5',
    contract: 'CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA',
    name: 'USDC',
    org: 'unknown',
    domain: 'centre.io',
    decimals: 7,
  },
  {
    code: 'mZAR',
    issuer: 'GC57ZJLYGUOMGDGPD5XFDOTQHQER3QL6B72SPTR3XTEKRY3HJ75NCNBL',
    contract: 'CATPX7RKNK53ZY5X5X375V72OKZFYQVLTC6XLVJA2XEMEXOMEJHLDPER',
    name: 'mZAR',
    org: 'unknown',
    domain: 'mesh-dev-tokens.mesh.trade',
    decimals: 7,
  },
  {
    code: 'USDF',
    issuer: 'GCIGYSZXK3XBLGJXRQ747LMLIKEZXOEETHQ2Y725AIIIEFBPVY3NDDHL',
    contract: 'CDOSPERYB764H7WYAE3QVM3HIQW5HI7E75R7CKGVUVGN76EKGO5BOPU7',
    name: 'USDF',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'AQUA',
    issuer: 'GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER',
    contract: 'CDNVQW44C3HALYNVQ4SOBXY5EWYTGVYXX6JPESOLQDABJI5FC5LTRRUE',
    name: 'AQUA',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'ZARZ',
    issuer: 'GCIAIV6KT5DUPJGYTRKOETBC3QOOMDQ5XR3RGN2TFFAZG6655ZI5O5BQ',
    contract: 'CCCBQZXHU2FFSDHK2O2CDXW3IPRTFJO6W3H7O2D4FROWRVQQFJQUYDN6',
    name: 'ZARZ',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'USDT',
    issuer: 'GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER',
    contract: 'CBL6KD2LFMLAUKFFWNNXWOXFN73GAXLEA4WMJRLQ5L76DMYTM3KWQVJN',
    name: 'USDT',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'USDCAllow',
    issuer: 'GAWZGWFOURKXZ4XYXBGFADZM4QIG6BJNM74XIZCEIU3BHM62RN2MDEZN',
    contract: 'CAZ5AGSIK7EGAPUT5EBEBGZXZCHHR4G7NR6VQE55HBEV6ESZ2P7N4GEU',
    name: 'USDCAllow',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'USDC',
    issuer: 'GDQOE23CFSUMSVQK4Y5JHPPYK73VYCNHZHA7ENKCV37P6SUEO6XQBKPP',
    contract: 'CDTY3P6OVY3SMZXR3DZA667NAXFECA6A3AOZXEU33DD2ACBY43CIKDPT',
    name: 'USDC',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'ETB',
    issuer: 'GCOPEOXVHXLHTV676E7WJ2Y7UBBSEGUEL4VQ4OIT6YUPMXMI3QUNBON6',
    contract: 'CBU5DCZZU5STXX4LZL4A4VECC7AHYMA3TGFUTUKZ7WWL6Y2K7NOAAFOG',
    name: 'ETB',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'USDC',
    issuer: 'GATALTGTWIOT6BUDBCZM3Q4OQ4BO2COLOAZ7IYSKPLC2PMSOPPGF5V56',
    contract: 'CAQCFVLOBK5GIULPNZRGATJJMIZL5BSP7X5YJVMGCPTUEPFM4AVSRCJU',
    name: 'USDC',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'USDC',
    issuer: 'GAHPYWLK6YRN7CVYZOO4H3VDRZ7PVF5UJGLZCSPAEIKJE2XSWF5LAGER',
    contract: 'CAZRY5GSFBFXD7H6GAFBA5YGYQTDXU4QKWKMYFWBAZFUCURN3WKX6LF5',
    name: 'USDC',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'EURC',
    issuer: 'GB3Q6QDZYTHWT7E5PVS3W7FUT5GVAFC5KSZFFLPU25GO7VTC3NM2ZTVO',
    contract: 'CCUUDM434BMZMYWYDITHFXHDMIVTGGD6T2I5UKNX5BSLXLW7HVR4MCGZ',
    name: 'EURC',
    org: 'unknown',
    domain: 'circle.com',
    decimals: 7,
  },
  {
    code: 'AQUA',
    issuer: 'GAV273QGEOQBPUL7USV3OOAZST2ER6AJNBDOYCLMK7DGWC73UJIOO4OQ',
    contract: 'CAV4E6REFNZMVG3I5LV6RYVV6DS3QKGCB5TNTHHBRTXRLD4G4GOLQAXC',
    name: 'AQUA',
    org: 'unknown',
    domain: 'mesh-dev-tokens.mesh.trade',
    decimals: 7,
  },
  {
    code: 'USDZ',
    issuer: 'GBI5Y3ND3N7UGNLBIKTSYLADVWVD2YY4ZSBQQU5C2S2CGKATFGJNWUC5',
    contract: 'CCS6HB5H4QHNBXUVLJLBBTLS6ITNN6ZAO2YT5W63ET6ORNGSLCFHTELU',
    name: 'USDZ',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'TEST2',
    issuer: 'GAHRRYTIJIUCI3DFKMVNC7TPAUZE6JLUGZS6VY7K5JIXOKQFIEDWN2NS',
    contract: 'CA3V4V6UOB6432B3BO7GP5ACCBUJOZUUN4NX7YFTUR7QNP3P62YI776Z',
    name: 'TEST2',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'RAHAT',
    issuer: 'GCVLRQHGZYG32HZE3PKZ52NX5YFCNFDBUZDLUXQYMRS6WVBWSUOP5IYE',
    contract: 'CB5ODLE3AWHEFFDPSKWEDLDX74YXKDJRMRODIWUMVDNUGTRSD3VRYU2B',
    name: 'RAHAT',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'DAMX',
    issuer: 'GC2GUPA2OUWPU67BBGBJFWE626V5YIVLFFYUQZRIIKLWRSKHN3PJOKS7',
    contract: 'CBHHQRUACD42AZ2ZNB4DK54JPCZQD2AYDPCB3DVS7JDN22S5CYGUOZCX',
    name: 'DAMX',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'eUAH',
    issuer: 'GCMNDHDRSBP6ZBVSSDXGAUR7JUJHZF3QA66UAZNFLOVTPJ7HAAUE4M5L',
    contract: 'CAKRXTZ6LXNOCMVJRNL2N5P4RO5Y4UMOVRS5I2JEWKIWDRGD5PVW34US',
    name: 'eUAH',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'ATUSD',
    issuer: 'GBT4VVTDPCNA45MNWX5G6LUTLIEENSTUHDVXO2AQHAZ24KUZUPLPGJZH',
    contract: 'CBBWL5EOM366OOUIUMBDC5J35DIPA26Z6VBNAKTGGBKPGX5DJOWXHQQC',
    name: 'ATUSD',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'XMUSD',
    issuer: 'GAZKBG4Q7JCKTY5K5Q42SSUW6F3O6OE2SLP7PYRVW4NYSEPIUMV5G2MN',
    contract: 'CDMUQY2ZHWIGXSTHPHX53ACR76OLXCCAAKQWQWUS2JNAH6SZEXMRU6R2',
    name: 'XMUSD',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'TSusdc',
    issuer: 'GBVMUAJ7XOCRXSKXBLZ5IXYPIQWHRIDBHIYGLVXIY6MA5WOBKJBJ4AJE',
    contract: 'CCV7GVGPEAPR4QPH4G46QHVI7BOTQFSYOMQTSK4Q7QNDKNHZFF2SP2WU',
    name: 'TSusdc',
    org: 'unknown',
    domain: 'ts.blocktimefinancial.com',
    decimals: 7,
  },
  {
    code: 'USD',
    issuer: 'GANCKFGWXAEMJ53GP6VIEHIHRCFO3CIG5ID54WEO7YDR32Y6OG4N2PTU',
    contract: 'CB2BPNOJQ2GP4DZZG43WIZKQ63AIPG56NL23SNK33O4HH5MZNBAOC34C',
    name: 'USD',
    org: 'unknown',
    domain: 'owny.com',
    decimals: 7,
  },
  {
    code: 'STX',
    issuer: 'GC2GUPA2OUWPU67BBGBJFWE626V5YIVLFFYUQZRIIKLWRSKHN3PJOKS7',
    contract: 'CDQMMPDCRS6AVGTW7IQ4H5SEHUR4AYTLMJN2DQ3JMFPWPXJO6VEZRC6I',
    name: 'STX',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'eUAH',
    issuer: 'GDZOER7YB2DXVHULTDJTYIQPFTAWH42UQCYQ6VXVFW75MHHDXEOQKD6X',
    contract: 'CDVRRDX5BNK4HLRC464IFOTCCEVGUONEGMUAKVBEJJUCKXQVXKKE3S6T',
    name: 'eUAH',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'ARST',
    issuer: 'GB7TAYRUZGE6TVT7NHP5SMIZRNQA6PLM423EYISAOAP3MKYIQMVYP2JO',
    contract: 'CBONHS7P3WHN24SUWIQIEU4CMX2YX3OMQYIPIFBCOURXDW3LPKM4HRY3',
    name: 'ARST',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'USDC',
    issuer: 'GBL74ETHLQJQUQW7YQT4KO3HJVR74TIHSBW6ENRBSFHUTATBRKKLGW4Y',
    contract: 'CBAJGVMQQGGECN7NRSJGWD3Z4JVZAK662P6MPYRWXGRJEIWBNOONADER',
    name: 'USDC',
    org: 'unknown',
    domain: 'dev.blocktimefinancial.com',
    decimals: 7,
  },
  {
    code: 'BO1',
    issuer: 'GC34BWAPF4TI4MTITVFXBDCITGLKBSAYIBVXQNYGJYVGZCH57OPSHUAS',
    contract: 'CBN2MBW4AFEHXMLE5ADTAWFOQKEHBYTVO62AZ7DTQONACYE26VFPHKVA',
    name: 'BO1',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'LPI',
    issuer: 'GCMAYD75HBQUUAN42CAZKWG6KI76GK4RDRB5BBHHTPK665CDV7F7YRNI',
    contract: 'CCDT24RJJA2OIOX23WLJLOO5Z2RMTRCST2ONPWW2WXF7PZLSIY22GEGU',
    name: 'LPI',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'EMT',
    issuer: 'GDF3PRTHMNNNI4GFDE7KRS43EPJFOUKMKTKCJOWNAAAEBCAGNMRATLGQ',
    contract: 'CDVFL2WH7VWF2MLSPKS3Y33MVUL7HTD6A6S6HRLH3MU4L2FAREMF35GE',
    name: 'EMT',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'LPT',
    issuer: 'GCMAYD75HBQUUAN42CAZKWG6KI76GK4RDRB5BBHHTPK665CDV7F7YRNI',
    contract: 'CBG2EPYRUVGMIRPJIYM6ZCTEOFKIZ4DRJJT7SQ52LXOBCOZ2A2LVTZLR',
    name: 'LPT',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'WUSD',
    issuer: 'GAOEMJYVBNUDU643U2QC3FL6YOJXES357HRM5WUW4TK36S4FEOP6DJAV',
    contract: 'CBPTTE7AHBFYH2NINPWCAWCBKBJA6AG5GBGZKHLMCKWPLVOQXVMNY6P2',
    name: 'WUSD',
    org: 'unknown',
    domain: 'stellarinfodev.wisdomtree.com',
    decimals: 7,
  },
  {
    code: 'TSaml001',
    issuer: 'GBJEGZIRNCPRJSONVCAIN5OL7UHJGEREOYRAVXKSMZLIRTAP2CJH2HGN',
    contract: 'CD2JSCD7VUYN6PMEJ7IMK2N7HZH7BGGFUVBMW5UU7BG6DKRGUJLBNHGY',
    name: 'TSaml001',
    org: 'unknown',
    domain: 'ts.blocktimefinancial.com',
    decimals: 7,
  },
  {
    code: 'TSkyc365',
    issuer: 'GBJEGZIRNCPRJSONVCAIN5OL7UHJGEREOYRAVXKSMZLIRTAP2CJH2HGN',
    contract: 'CA7AFHBWYAETZNEP2BO2I4KSFA5WSRCQ2AKCP7V54NYNF4REXC6RY7NZ',
    name: 'TSkyc365',
    org: 'unknown',
    domain: 'ts.blocktimefinancial.com',
    decimals: 7,
  },
  {
    code: 'CARBON',
    issuer: 'GDT5XM5C5STQZS5R3F4CEGKJWKDVWBIWBEV4TIYV5MDVVMKA775T4OKY',
    contract: 'CCVMSAUB5RSCN7VFA2GESPVGRBNDHLQG5YDA7DST63OXJB5YBZGKEUVU',
    name: 'CARBON',
    org: 'unknown',
    domain: 'testnet-api.stellarcarbon.io',
    decimals: 7,
  },
  {
    code: 'DOCS',
    issuer: 'GBAODGRTFUH2LYMTFABF53KBHX36WWWEGMAFCZMNAUZSDWMVEHRPRK7H',
    contract: 'CAP7YGQ4UM7KTNCFPSZYUCFREZSMEAOJ3T2CYT5PE6SLQPTHGKD6XO7H',
    name: 'DOCS',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'XABC',
    issuer: 'GDRENIVHJEFIVEVB74UEGNKWQBPPDMVIIDSVYDKTNJXDCJXBDGVZWHOE',
    contract: 'CCHTD2PVJ4SYWXWFLWZD7LZNNHMRGAI24M5DYTVRQW5STRXVQAWGMDS7',
    name: 'XABC',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'T001',
    issuer: 'GDUO3WZRCZ5XWJBKKX5CRW6I6QBE4UDXOIJCCNVPSA6P4TQ2WF3KZWWU',
    contract: 'CD5WE2K3NFTTG7W4MUKVDWHWU5SVYNIN6QOL7SROK5AGG4FXT26BLJT7',
    name: 'T001',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'USDO',
    issuer: 'GADIJX2LINAXDID5GAWYMTGT35MEGTULI32MSWOMGPA5MQY7URZDYWJD',
    contract: 'CC2IAY7JRMK5NL6IKPGS26SPIABOJJTO3XNAHNG2UUKJ377SHZ77A535',
    name: 'USDO',
    org: 'unknown',
    domain: 'bc.sandbox.orokii.com',
    decimals: 7,
  },
  {
    code: 'TFT',
    issuer: 'GA47YZA3PKFUZMPLQ3B5F2E3CJIB57TGGU7SPCQT2WAEYKN766PWIMB3',
    contract: 'CCUDLQYR27JTUQVOIRQAB6S5IV7QEOGAJYO5QIHGSVY53DBGFWQB7OSD',
    name: 'TFT',
    org: 'unknown',
    domain: 'www2.threefold.io',
    decimals: 7,
  },
  {
    code: 'DOCS',
    issuer: 'GDN4M7JP2MWGFCGKQ5VOZKV3EQTXM6LVXJG2CAAZEOCFVCXSHPHF3ZEF',
    contract: 'CAY3YBVBFKIWH57ZNZ4D3FYM4AWGTG22J25V3YSMTGDTLFWYTT4V5P3I',
    name: 'DOCS',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'TEST2',
    issuer: 'GAIG422GCQ5NPTYE34NYBELVKV543LMAQW3MTHEDZB7DPE673AOKLEXO',
    contract: 'CCUOWUMEIBXWLTMPCLPUPL5AK65EZLU2TVCJXIX55VS7GIU6SLFGWRFF',
    name: 'TEST2',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'NEWASSET',
    issuer: 'GC2GUPA2OUWPU67BBGBJFWE626V5YIVLFFYUQZRIIKLWRSKHN3PJOKS7',
    contract: 'CCPEW27PHHFKCD2IW5KWUHKWQM7PEQZMTOLJII7BSHTQYANYPFIKSL7Y',
    name: 'NEWASSET',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'SAT1',
    issuer: 'GCNTYYJORSDB3RYWVCNCWK4U5SCCOOZKOXVUQZP6KCVRYLAP6TWWJ3C5',
    contract: 'CC6RNAVJWE4NRDZH64DLN4WD6PKUMP7DHDMS6SNEX5VHGJJDE57JZ6FU',
    name: 'SAT1',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'BLND',
    issuer: 'GATALTGTWIOT6BUDBCZM3Q4OQ4BO2COLOAZ7IYSKPLC2PMSOPPGF5V56',
    contract: 'CB22KRA3YZVCNCQI64JQ5WE7UY2VAV7WFLK6A2JN3HEX56T2EDAFO7QF',
    name: 'BLND',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'wETH',
    issuer: 'GATALTGTWIOT6BUDBCZM3Q4OQ4BO2COLOAZ7IYSKPLC2PMSOPPGF5V56',
    contract: 'CAZAQB3D7KSLSNOSQKYD2V4JP5V2Y3B4RDJZRLBFCCIXDCTE3WHSY3UE',
    name: 'wETH',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'wBTC',
    issuer: 'GATALTGTWIOT6BUDBCZM3Q4OQ4BO2COLOAZ7IYSKPLC2PMSOPPGF5V56',
    contract: 'CAP5AMC2OHNVREO66DFIN6DHJMPOBAJ2KCDDIMFBR7WWJH5RZBFM3UEI',
    name: 'wBTC',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'USDPEND',
    issuer: 'GDQHX2HEAIDCT36HIKTBURLIL74PJ625SOR7PRJZOK32T3Z5CBW6GGQB',
    contract: 'CBCRIITNA4O3PBZCM7J4WIAGEVXW7HEEX55QIBZC3CFSYK3LYJ65WZHL',
    name: 'USDPEND',
    org: 'unknown',
    decimals: 7,
  },
  {
    code: 'CTAUSD',
    issuer: 'GDIWE3NFBUBO5IMU2KYRJ56S3DDDRZ7SMAZJIB3JD5SY6QSDW4O33Y6D',
    contract: 'CB5UJQSJXL5D2EW7OYJCZE2UF5BC35IR2ZYLMSPTU3E2PG2AXKCBZHVM',
    name: 'CTAUSD',
    org: 'unknown',
    domain: 'owny.com',
    decimals: 7,
  },
]

export const getTokenByCode = (code: string) => {
  return baseTokens.find((token) => token.code === code)
}

export const getTokenByContract = (contract: string) => {
  return baseTokens.find((token) => token.contract === contract)
}
