import {
  SUSHISWAP_ENABLED_NETWORKS,
  TRIDENT_ENABLED_NETWORKS,
} from '@sushiswap/graph-config'

export const TOKENS_SUPPORTED_CHAIN_IDS = [
  ...TRIDENT_ENABLED_NETWORKS,
  ...SUSHISWAP_ENABLED_NETWORKS,
]
