#!/usr/bin/env node
"use strict";

var _chunkPFLUUIESjs = require('./chunk-PFLUUIES.js');


var _chunkM24XL6CIjs = require('./chunk-M24XL6CI.js');
require('./chunk-WXLEX5S3.js');

// src/cli-default.ts
_chunkPFLUUIESjs.main.call(void 0, ).catch(_chunkM24XL6CIjs.handleError);
