/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { UniswapInterfaceMulticall } from "./UniswapInterfaceMulticall";

export { UniswapInterfaceMulticall__factory } from "./factories/UniswapInterfaceMulticall__factory";
