import { ChainId } from '../chain/index.js'
import { Token } from '../currency/token.js'

export const LSDS = {
  [ChainId.ARBITRUM]: [],
  [ChainId.ARBITRUM_NOVA]: [],
  [ChainId.AVALANCHE]: [],
  [ChainId.BASE]: [],
  [ChainId.BOBA]: [],
  [ChainId.BOBA_AVAX]: [],
  [ChainId.BOBA_BNB]: [],
  [ChainId.BSC]: [],
  [ChainId.BTTC]: [],
  [ChainId.CELO]: [],
  [ChainId.ETHEREUM]: [
    new Token({
      chainId: ChainId.ETHEREUM,
      address: '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84',
      decimals: 18,
      symbol: 'StETH',
      name: 'Lido Staked ETH',
    }),
    new Token({
      chainId: ChainId.ETHEREUM,
      address: '0xae78736cd615f374d3085123a210448e74fc6393',
      decimals: 18,
      symbol: 'rETH',
      name: 'Rocket Pool ETH',
    }),
  ],
  [ChainId.FANTOM]: [],
  [ChainId.FILECOIN]: [],
  [ChainId.FUSE]: [],
  [ChainId.GNOSIS]: [],
  [ChainId.HARMONY]: [],
  [ChainId.HAQQ]: [],
  [ChainId.HECO]: [],
  [ChainId.KAVA]: [],
  [ChainId.LINEA]: [],
  [ChainId.METIS]: [],
  [ChainId.MOONBEAM]: [],
  [ChainId.MOONRIVER]: [],
  [ChainId.OKEX]: [],
  [ChainId.OPTIMISM]: [],
  [ChainId.POLYGON]: [],
  [ChainId.POLYGON_ZKEVM]: [],
  [ChainId.SCROLL]: [],
  [ChainId.TELOS]: [],
  [ChainId.THUNDERCORE]: [],
  [ChainId.CORE]: [],
  [ChainId.ZETACHAIN]: [],
  [ChainId.CRONOS]: [],
  [ChainId.BLAST]: [],
  [ChainId.SKALE_EUROPA]: [],
  [ChainId.ROOTSTOCK]: [],
  [ChainId.PALM]: [],
  [ChainId.ZKSYNC_ERA]: [],
  // TESTNETS
  [ChainId.POLYGON_TESTNET]: [],
  [ChainId.FANTOM_TESTNET]: [],
  [ChainId.BSC_TESTNET]: [],
  [ChainId.ARBITRUM_TESTNET]: [],
  [ChainId.AVALANCHE_TESTNET]: [],
  [ChainId.SEPOLIA]: [],
} as const satisfies Record<ChainId, Token[]>
