import * as t from "io-ts";
import { BN } from "ethereumjs-util";
export declare type RpcBlock = t.TypeOf<typeof rpcBlock>;
export declare const rpcBlock: t.TypeC<{
    transactions: t.ArrayC<t.Type<Buffer, Buffer, unknown>>;
    number: t.Type<BN | null, BN | null, unknown>;
    hash: t.Type<Buffer | null, Buffer | null, unknown>;
    parentHash: t.Type<Buffer, Buffer, unknown>;
    nonce: t.Type<Buffer | undefined, Buffer | undefined, unknown>;
    sha3Uncles: t.Type<Buffer, Buffer, unknown>;
    logsBloom: t.Type<Buffer, Buffer, unknown>;
    transactionsRoot: t.Type<Buffer, Buffer, unknown>;
    stateRoot: t.Type<Buffer, Buffer, unknown>;
    receiptsRoot: t.Type<Buffer, Buffer, unknown>;
    miner: t.Type<Buffer, Buffer, unknown>;
    difficulty: t.Type<BN, BN, unknown>;
    totalDifficulty: t.Type<BN, BN, unknown>;
    extraData: t.Type<Buffer, Buffer, unknown>;
    size: t.Type<BN, BN, unknown>;
    gasLimit: t.Type<BN, BN, unknown>;
    gasUsed: t.Type<BN, BN, unknown>;
    timestamp: t.Type<BN, BN, unknown>;
    uncles: t.ArrayC<t.Type<Buffer, Buffer, unknown>>;
    mixHash: t.Type<Buffer | undefined, Buffer | undefined, unknown>;
    baseFeePerGas: t.Type<BN | undefined, BN | undefined, unknown>;
}>;
export declare type RpcBlockWithTransactions = t.TypeOf<typeof rpcBlockWithTransactions>;
export declare const rpcBlockWithTransactions: t.TypeC<{
    transactions: t.ArrayC<t.TypeC<{
        blockHash: t.Type<Buffer | null, Buffer | null, unknown>;
        blockNumber: t.Type<BN | null, BN | null, unknown>;
        from: t.Type<Buffer, Buffer, unknown>;
        gas: t.Type<BN, BN, unknown>;
        gasPrice: t.Type<BN, BN, unknown>;
        hash: t.Type<Buffer, Buffer, unknown>;
        input: t.Type<Buffer, Buffer, unknown>;
        nonce: t.Type<BN, BN, unknown>;
        to: t.Type<Buffer | null | undefined, Buffer | null | undefined, unknown>;
        transactionIndex: t.Type<BN | null, BN | null, unknown>;
        value: t.Type<BN, BN, unknown>;
        v: t.Type<BN, BN, unknown>;
        r: t.Type<BN, BN, unknown>;
        s: t.Type<BN, BN, unknown>;
        type: t.Type<BN | undefined, BN | undefined, unknown>;
        chainId: t.Type<BN | null | undefined, BN | null | undefined, unknown>;
        accessList: t.Type<{
            address: Buffer;
            storageKeys: Buffer[] | null;
        }[] | undefined, {
            address: Buffer;
            storageKeys: Buffer[] | null;
        }[] | undefined, unknown>;
        maxFeePerGas: t.Type<BN | undefined, BN | undefined, unknown>;
        maxPriorityFeePerGas: t.Type<BN | undefined, BN | undefined, unknown>;
    }>>;
    number: t.Type<BN | null, BN | null, unknown>;
    hash: t.Type<Buffer | null, Buffer | null, unknown>;
    parentHash: t.Type<Buffer, Buffer, unknown>;
    nonce: t.Type<Buffer | undefined, Buffer | undefined, unknown>;
    sha3Uncles: t.Type<Buffer, Buffer, unknown>;
    logsBloom: t.Type<Buffer, Buffer, unknown>;
    transactionsRoot: t.Type<Buffer, Buffer, unknown>;
    stateRoot: t.Type<Buffer, Buffer, unknown>;
    receiptsRoot: t.Type<Buffer, Buffer, unknown>;
    miner: t.Type<Buffer, Buffer, unknown>;
    difficulty: t.Type<BN, BN, unknown>;
    totalDifficulty: t.Type<BN, BN, unknown>;
    extraData: t.Type<Buffer, Buffer, unknown>;
    size: t.Type<BN, BN, unknown>;
    gasLimit: t.Type<BN, BN, unknown>;
    gasUsed: t.Type<BN, BN, unknown>;
    timestamp: t.Type<BN, BN, unknown>;
    uncles: t.ArrayC<t.Type<Buffer, Buffer, unknown>>;
    mixHash: t.Type<Buffer | undefined, Buffer | undefined, unknown>;
    baseFeePerGas: t.Type<BN | undefined, BN | undefined, unknown>;
}>;
//# sourceMappingURL=block.d.ts.map