// This file is auto-generated by scripts/update-data-api-types.ts
export const BladeChainIds = [
  1, 137, 1101, 10, 42161, 8453, 5000, 747474, 56,
] as const
export type BladeChainId = (typeof BladeChainIds)[number]
export function isBladeChainId(value: number): value is BladeChainId {
  return BladeChainIds.includes(value as BladeChainId)
}
