// This file is auto-generated by scripts/update-data-api-types.ts
export const PoolChainIds = [42161,42170,43114,8453,288,56,42220,1,250,100,137,534352,314,10,59144,2046399126,30,146,43111,747474,81457,11155111,129399,737373,1101,5000] as const
export type PoolChainId = typeof PoolChainIds[number]
export function isPoolChainId(value: number): value is PoolChainId {return PoolChainIds.includes(value as PoolChainId)}