// This file is auto-generated by scripts/update-data-api-types.ts
export const SmartPoolChainIds = [1, 8453] as const
export type SmartPoolChainId = (typeof SmartPoolChainIds)[number]
export function isSmartPoolChainId(value: number): value is SmartPoolChainId {
  return SmartPoolChainIds.includes(value as SmartPoolChainId)
}
