// This file is auto-generated by scripts/update-data-api-types.ts
export const TokenListV2ChainIds = [42161,42170,43114,8453,288,56288,56,42220,1,250,100,11235,137,534352,2222,1088,199,314,7000,1116,108,10,59144,81457,2046399126,30,146,43111,747474,11155111,129399,25,5000,324,169,34443,167000,810180,33139,999,80094,9745,1101] as const
export type TokenListV2ChainId = typeof TokenListV2ChainIds[number]
export function isTokenListV2ChainId(value: number): value is TokenListV2ChainId {return TokenListV2ChainIds.includes(value as TokenListV2ChainId)}