// This file is auto-generated by scripts/update-data-api-types.ts
export const TrendingTokensChainIds = [
  42161, 42170, 43114, 8453, 288, 56, 42220, 1, 250, 100, 137, 534352, 10,
  59144, 2046399126, 30, 146, 43111, 747474, 81457, 25, 5000, 324, 169, 34443,
  167000, 810180, 33139, 999, 80094, 9745, 143, 4326, 196, 1101, -5,
] as const
export type TrendingTokensChainId = (typeof TrendingTokensChainIds)[number]
export function isTrendingTokensChainId(
  value: number,
): value is TrendingTokensChainId {
  return TrendingTokensChainIds.includes(value as TrendingTokensChainId)
}
