name: Chromatic

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/chromatic.yml"
      - "apps/storybook/**"
      - "packages/hooks/**"
      - "packages/telemetry/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "pnpm-workspace.yaml"
      - "turbo.json"
      - ".github/actions/install/**"
      - "config/tailwindcss/**"
      - "packages/ui/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          node-version: 24.16.0
        env:
          TRADING_VIEW_GH_READ_TOKEN: ${{ secrets.TRADING_VIEW_GH_READ_TOKEN }}
      - name: Build Storybook dependencies
        run: pnpm exec turbo run build --filter=@sushiswap/storybook^...
      - name: Check Storybook types
        run: pnpm --filter @sushiswap/storybook check
      - name: Publish to Chromatic
        run: pnpm --filter @sushiswap/storybook chromatic --exit-once-uploaded
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
